<?php
/**
 * Authenticated AJAX controller and renderer for Manual Studio.
 *
 * @package AIContentStudio
 */

if ( ! defined( 'ABSPATH' ) ) { exit; }

final class AICS_Manual_Studio_Wizard_Controller {
	private const AJAX_ACTION='aics_manual_wizard';
	private const NONCE_ACTION='aics_manual_wizard';
	private const TONES=array('professional'=>'Professional','friendly'=>'Friendly','conversational'=>'Conversational','informative'=>'Informative','persuasive'=>'Persuasive');
	private const LENGTHS=array('short'=>'Short — 600–800 words','medium'=>'Standard — 1000–1400 words','long'=>'Long — 1800–2400 words');
	private const FORMATS=array('plain'=>'Plain','how_to'=>'How-to guide','listicle'=>'List article','thought_leadership'=>'Thought leadership');

	public static function register():void{add_action('wp_ajax_'.self::AJAX_ACTION,array(self::class,'handle'));}
	private static function permission():void{if(!is_user_logged_in()||!current_user_can(\AIContentStudio\Core\Permissions::manage())){wp_send_json_error(array('code'=>'permission_denied','message'=>__('You are not allowed to use Manual Studio.','ai-content-studio')),403);}}
	private static function state():AICS_Manual_Wizard_State_Service{return new AICS_Manual_Wizard_State_Service(get_current_user_id());}

	public static function render_page():void{$state=self::state();?><div class="wrap aics-admin-wrap aics-content-studio-page aics-wizard-page"><header class="aics-page-header"><h1 class="aics-page-title"><?php esc_html_e('Create Content','ai-content-studio');?></h1><p class="aics-page-description"><?php esc_html_e('Create, review, illustrate, and optimize one WordPress article in a guided workflow.','ai-content-studio');?></p></header><noscript><div class="notice notice-warning"><p><?php esc_html_e('JavaScript is required for the guided wizard. Existing work remains saved; enable JavaScript and reload this page.','ai-content-studio');?></p></div></noscript><div id="aics-manual-wizard" class="aics-wizard" data-endpoint="<?php echo esc_url(admin_url('admin-ajax.php'));?>" data-action="<?php echo esc_attr(self::AJAX_ACTION);?>" data-nonce="<?php echo esc_attr(wp_create_nonce(self::NONCE_ACTION));?>"><?php self::render_shell($state);?></div></div><?php }

	public static function handle():void{self::permission();check_ajax_referer(self::NONCE_ACTION,'nonce');$operation=isset($_POST['operation'])?sanitize_key(wp_unslash($_POST['operation'])):'';$allowed=array('render','navigate','generate_ideas','regenerate_ideas','generate_article','save_article','create_draft','generate_image','save_image_prompt','refresh_image_prompt','save_alt','generate_seo','save_seo','apply_seo','reset');if(!in_array($operation,$allowed,true)){self::fail('invalid_action',__('The requested wizard action is invalid.','ai-content-studio'));}$state=self::state();$locked=in_array($operation,array('generate_ideas','regenerate_ideas','generate_article','create_draft','generate_image','generate_seo','apply_seo'),true);if($locked){if(!$state->acquire($operation)){self::fail('operation_in_progress',__('This operation is already running in another request. Please wait and retry.','ai-content-studio'));}register_shutdown_function(array($state,'release'),$operation);}try{$message=self::dispatch($operation,$state);self::respond($state,$message);}catch(Throwable $e){self::fail('wizard_operation_failed',__('Something went wrong while processing this step. Your existing work has been preserved.','ai-content-studio'));}}

	private static function dispatch(string $op,AICS_Manual_Wizard_State_Service $state):string{switch($op){case'render':return'';case'navigate':$step=sanitize_key((string)($_POST['step']??''));if(!$state->move_to($step)){self::fail('step_not_allowed',__('That step is not available yet.','ai-content-studio'));}return __('Step restored.','ai-content-studio');case'reset':$state->reset();return __('A new content workflow is ready. Existing articles and posts were preserved.','ai-content-studio');case'generate_ideas':return self::generate_ideas($state,false);case'regenerate_ideas':return self::generate_ideas($state,true);case'generate_article':return self::generate_article($state);case'save_article':return self::save_article($state,false);case'create_draft':self::save_article($state,true);return self::create_draft($state);case'generate_image':return self::generate_image($state);case'save_image_prompt':return self::save_image_prompt($state,false);case'refresh_image_prompt':return self::save_image_prompt($state,true);case'save_alt':return self::save_alt($state);case'generate_seo':return self::generate_seo($state);case'save_seo':return self::save_seo($state);case'apply_seo':self::save_seo($state);return self::apply_seo($state);}return'';}

	private static function generate_ideas(AICS_Manual_Wizard_State_Service $state,bool $stored):string{$scalar=static fn($k):string=>isset($_POST[$k])&&is_string($_POST[$k])?wp_unslash($_POST[$k]):'';$context=$stored?$state->context():array('business_context'=>substr(trim(sanitize_textarea_field($scalar('business_context'))),0,3000),'topic_keyword'=>substr(trim(sanitize_text_field($scalar('topic_keyword'))),0,250),'tone'=>sanitize_key($scalar('tone')),'article_length'=>sanitize_key($scalar('article_length')),'content_format'=>sanitize_key($scalar('content_format')),'idea_instructions'=>substr(sanitize_textarea_field($scalar('idea_instructions')),0,3000),'article_instructions'=>substr(sanitize_textarea_field($scalar('article_instructions')),0,3000),'featured_image_instructions'=>substr(sanitize_textarea_field($scalar('featured_image_instructions')),0,3000),'seo_settings'=>$state->context()['seo_settings']);if(''===$context['business_context']||''===$context['topic_keyword']||!isset(self::TONES[$context['tone']])||!isset(self::LENGTHS[$context['article_length']])||!isset(self::FORMATS[$context['content_format']])){self::fail('invalid_context',__('Complete the required context fields with valid options.','ai-content-studio'));}if(!AICS_Settings::has_openai_api_key()){self::fail('missing_api_key',__('Configure the OpenAI API key before generating ideas.','ai-content-studio'));}$state->set('content_inputs',$context);$response=(new AICS_AI_Engine())->generate_blog_ideas($context);if(!$response->is_success()){self::fail($response->get_error_code(),__('Ideas could not be generated. Your context has been preserved.','ai-content-studio'));}$data=$response->get_data();if(!is_array($data)||!is_array($data['ideas']??null)){self::fail('invalid_idea_format',__('The provider returned an invalid idea set.','ai-content-studio'));}$state->set('content_ideas',array('ideas'=>$data['ideas'],'generated_at'=>time(),'model'=>AICS_Settings::get_openai_model()));$state->delete('selected_idea');$state->move_to('ideas');return __('Five content ideas are ready.','ai-content-studio');}

	private static function generate_article(AICS_Manual_Wizard_State_Service $state):string{$id=sanitize_key((string)($_POST['selected_idea_id']??''));$ideas=$state->ideas()['ideas']??array();$previous=$state->selected_idea();$selected=null;foreach($ideas as $idea){if(is_array($idea)&&hash_equals((string)($idea['id']??''),$id)){$selected=$idea;break;}}if(!$selected){self::fail('invalid_selected_idea',__('Select one generated idea.','ai-content-studio'));}$context=$state->context();$response=(new AICS_AI_Engine())->generate_article_draft($context,$selected);if(!$response->is_success()){self::fail($response->get_error_code(),__('The article could not be generated. Your selected idea has been preserved.','ai-content-studio'));}$article=$response->get_data();if(!is_array($article)){self::fail('invalid_article_format',__('The provider returned an invalid article.','ai-content-studio'));}$existing=$state->draft();$same=!empty($previous['id'])&&hash_equals((string)$previous['id'],(string)$selected['id']);$saved=(new AICS_Manual_Article_Persistence_Service())->persist_generated($article,get_current_user_id(),$same?absint($existing['article_id']??0):0);if(empty($saved['success'])){self::fail($saved['code']??'article_persistence_failed',__('The generated article could not be saved.','ai-content-studio'));}$state->set('selected_idea',$selected);$draft=array_merge($article,array('article_id'=>$saved['article_id'],'article_uuid'=>$saved['uuid'],'created_post_id'=>$saved['post_id'],'idea_id'=>$selected['id'],'generated_at'=>time(),'updated_at'=>time(),'model'=>AICS_Settings::get_openai_model(),'tone'=>$context['tone'],'length'=>$context['article_length']));$state->set('article_draft',$draft);$state->remember_article($saved['article_id']);$state->move_to('article');return __('Your article draft is ready for review.','ai-content-studio');}

	private static function save_article(AICS_Manual_Wizard_State_Service $state,bool $quiet):string{$draft=$state->draft();$id=absint($draft['article_id']??0);if(!$id){self::fail('article_missing',__('The active article could not be found.','ai-content-studio'));}$before=$state->article();$input=array('title'=>is_string($_POST['article_title']??null)?wp_unslash($_POST['article_title']):($draft['title']??''),'excerpt'=>is_string($_POST['article_excerpt']??null)?wp_unslash($_POST['article_excerpt']):($draft['excerpt']??''),'content'=>is_string($_POST['article_content']??null)?wp_unslash($_POST['article_content']):($draft['content']??''));$saved=(new AICS_Manual_Article_Persistence_Service())->update($id,$input,get_current_user_id());if(empty($saved['success'])){self::fail($saved['code']??'article_save_failed',__('The article could not be saved. Review the required fields.','ai-content-studio'));}$a=$saved['article'];if($before&&$before['content_hash']!==$a['content_hash']&&AICS_SEO_State::NOT_REQUESTED!==$before['seo_status']){(new AICS_Article_Repository())->persist_seo_application_error($id,'seo_content_changed',get_current_user_id());}$state->set('article_draft',array_merge($draft,array('title'=>$a['title'],'excerpt'=>$a['excerpt'],'content'=>$a['content'],'word_count'=>$a['word_count'],'updated_at'=>time())));return $quiet?'':__('Article changes saved.','ai-content-studio');}

	private static function create_draft(AICS_Manual_Wizard_State_Service $state):string{$draft=$state->draft();$idea=$state->selected_idea();$context=$state->context();$result=(new AICS_Manual_Article_Persistence_Service())->create_or_get_draft(absint($draft['article_id']),get_current_user_id(),array('primary_keyword'=>$idea['primary_keyword']??'','search_intent'=>$idea['search_intent']??'','tone'=>$context['tone'],'length'=>$context['article_length'],'generated_at'=>$draft['generated_at']??time()));if(empty($result['success'])){self::fail($result['code']??'draft_creation_failed',__('The WordPress draft could not be created.','ai-content-studio'));}$state->set('article_draft',array_merge($draft,array('created_post_id'=>$result['post_id'])));$state->move_to('image');return !empty($result['reused'])?__('The existing WordPress draft was reused.','ai-content-studio'):__('WordPress draft created.','ai-content-studio');}
	private static function generate_image(AICS_Manual_Wizard_State_Service $state):string{$article=$state->article();if(!$article){self::fail('article_missing',__('The active article could not be found.','ai-content-studio'));}$prompt=is_string($_POST['featured_image_prompt']??null)?wp_unslash($_POST['featured_image_prompt']):'';$result=(new AICS_Manual_Featured_Image_Service())->generate($article['id'],get_current_user_id(),$prompt);if(empty($result['success'])){self::fail($result['code']??'image_failed',$result['message']??__('The featured image could not be generated.','ai-content-studio'));}return $result['message']??__('Featured image generated and assigned.','ai-content-studio');}
	private static function save_image_prompt(AICS_Manual_Wizard_State_Service $state,bool $refresh):string{$article=$state->article();if(!$article){self::fail('article_missing',__('The active article could not be found.','ai-content-studio'));}$prompt=is_string($_POST['featured_image_prompt']??null)?wp_unslash($_POST['featured_image_prompt']):'';$result=(new AICS_Manual_Featured_Image_Service())->save_prompt($article['id'],get_current_user_id(),$prompt,$refresh);if(empty($result['success'])){self::fail($result['code']??'invalid_image_prompt',$result['message']??__('The featured image prompt could not be saved.','ai-content-studio'));}return $result['message'];}
	private static function save_alt(AICS_Manual_Wizard_State_Service $state):string{$article=$state->article();$alt=is_string($_POST['featured_image_alt_text']??null)?wp_unslash($_POST['featured_image_alt_text']):'';$result=$article?(new AICS_Manual_Featured_Image_Service())->save_alt_text($article['id'],get_current_user_id(),$alt):array();if(empty($result['success'])){self::fail($result['code']??'alt_save_failed',__('Image alt text could not be saved.','ai-content-studio'));}return __('Image alt text saved.','ai-content-studio');}
	private static function generate_seo(AICS_Manual_Wizard_State_Service $state):string{$article=$state->article();if(!$article){self::fail('article_missing',__('The active article could not be found.','ai-content-studio'));}if(empty($article['seo_focus_keyword'])){$result=(new AICS_Manual_SEO_Service())->generate($article['id'],get_current_user_id());if(empty($result['success'])){self::fail($result['code']??'seo_generation_failed',$result['message']??__('SEO data could not be generated.','ai-content-studio'));}}if(!$state->move_to('seo')){self::fail('step_not_allowed',__('Complete or skip the optional image step first.','ai-content-studio'));}return __('SEO data is ready for review.','ai-content-studio');}
	private static function seo_input():array{$scalar=static fn($k):string=>isset($_POST[$k])&&is_string($_POST[$k])?wp_unslash($_POST[$k]):'';return array('focus_keyword'=>$scalar('seo_focus_keyword'),'seo_title'=>$scalar('seo_title'),'meta_description'=>$scalar('seo_meta_description'),'slug'=>$scalar('seo_slug'),'excerpt'=>$scalar('seo_excerpt'),'categories'=>array_map('trim',explode(',',$scalar('seo_categories'))),'tags'=>array_map('trim',explode(',',$scalar('seo_tags'))),'image_alt_text'=>$scalar('seo_image_alt_text'));}
	private static function save_seo(AICS_Manual_Wizard_State_Service $state):string{$article=$state->article();if(!$article){self::fail('article_missing',__('The active article could not be found.','ai-content-studio'));}$result=(new AICS_Manual_SEO_Service())->save($article['id'],get_current_user_id(),self::seo_input());if(empty($result['success'])){self::fail($result['code']??'seo_save_failed',$result['message']??__('SEO data could not be saved.','ai-content-studio'));}return __('SEO data saved and reanalyzed.','ai-content-studio');}
	private static function apply_seo(AICS_Manual_Wizard_State_Service $state):string{$article=$state->article();$result=(new AICS_Manual_SEO_Application_Service())->apply($article['id'],get_current_user_id());if(empty($result['success'])){self::fail($result['code']??'seo_application_failed',$result['message']??__('SEO application requires attention. Your work was preserved.','ai-content-studio'));}$state->move_to('complete');return __('Your WordPress draft is complete and ready for final review.','ai-content-studio');}

	private static function respond(AICS_Manual_Wizard_State_Service $state,string $message):void{ob_start();self::render_shell($state);$html=ob_get_clean();wp_send_json_success(array('step'=>$state->current_step(),'progress'=>$state->progress(),'html'=>$html,'notice'=>array('type'=>'success','message'=>$message),'state'=>array('article_id'=>absint($state->draft()['article_id']??0))));}
	private static function fail(string $code,string $message):void{wp_send_json_error(array('code'=>sanitize_key($code),'message'=>$message),400);}
	private static function render_shell(AICS_Manual_Wizard_State_Service $state):void{$step=$state->current_step();?><div class="aics-wizard-live" aria-live="polite" aria-atomic="true"></div><?php self::render_progress($state);?><div class="aics-wizard-toolbar"><div class="aics-wizard-notice" role="status"></div><?php if('context'!==$step):?><button class="button" type="button" data-aics-reset><?php esc_html_e('Start New Content','ai-content-studio');?></button><?php endif;?></div><section class="aics-wizard-card" data-step="<?php echo esc_attr($step);?>" aria-busy="false"><?php self::render_step($step,$state);?></section><?php }
	private static function render_progress(AICS_Manual_Wizard_State_Service $state):void{$labels=array('context'=>'Context','ideas'=>'Ideas','article'=>'Article','image'=>'Image','seo'=>'SEO','complete'=>'Complete');$progress=$state->progress();?><nav class="aics-wizard-progress" aria-label="<?php esc_attr_e('Content creation progress','ai-content-studio');?>"><ol><?php foreach(AICS_Manual_Wizard_State_Service::STEPS as $i=>$step):$item=$progress[$step];?><li class="is-<?php echo esc_attr($item['status']);?>"><button type="button" data-aics-step="<?php echo esc_attr($step);?>" <?php disabled(!$item['accessible']);?> <?php echo 'active'===$item['status']?'aria-current="step"':'';?>><span class="aics-step-marker"><?php echo 'completed'===$item['status']?'✓':esc_html((string)($i+1));?></span><span class="aics-step-label"><?php echo esc_html($labels[$step]);?></span><span class="screen-reader-text"><?php echo esc_html(ucfirst($item['status']));?></span></button></li><?php endforeach;?></ol></nav><?php }
	private static function render_step(string $step,AICS_Manual_Wizard_State_Service $state):void{$file=AICS_PLUGIN_DIR.'templates/admin/manual-wizard/step-'.$step.'.php';if(is_readable($file)){include $file;}}
	public static function tones():array{return self::TONES;}public static function lengths():array{return self::LENGTHS;}public static function formats():array{return self::FORMATS;}
}
