<?php
if(!defined('ABSPATH')){exit;}
final class AICS_SEO_Quality_Analyzer{
	private const POWER=array('essential','proven','ultimate','powerful','simple','smart','complete','practical','effective','remarkable','exclusive','important');
	private const POSITIVE=array('best','easy','excellent','great','helpful','positive','successful','valuable','trusted','amazing');
	private const NEGATIVE=array('avoid','danger','difficult','failure','mistake','negative','risk','warning','worst','critical');
	private const BLOCKING_IDS=array('focus_keyword_exists','slug_structure','word_count','excerpt');
	public function analyze(AICS_SEO_Data $seo,array $article,array $settings,string $target):array{$d=$seo->to_adapter_data();$profile=AICS_SEO_Recommendation_Profile::get($target);$visible=$this->visible((string)($article['content']??''));$words=$this->words($visible);$keyword=$this->normalize($d['focus_keyword']);$occ=$this->phrase_count($visible,$keyword);$density=$words?round(($occ/$words)*100,2):0.0;$checks=array();$warnings=array();$blocking=array();$pass=0;$total=0;$check=function(string $id,bool $ok,string $message,bool $block=false,int $weight=5)use(&$checks,&$warnings,&$blocking,&$pass,&$total){$checks[]=array('id'=>$id,'passed'=>$ok,'message'=>$message,'weight'=>$weight);$total+=$weight;if($ok){$pass+=$weight;}elseif($block&&in_array($id,self::BLOCKING_IDS,true)){$blocking[]=array('id'=>$id,'message'=>$message);}else{$warnings[]=array('id'=>$id,'message'=>$message);}};
		$check('focus_keyword_exists',''!==$keyword,__('Focus keyword is present.','ai-content-studio'),true,10);$tl=$this->length($d['seo_title']);$check('title_length',$tl>=$profile['title_min']&&$tl<=$profile['title_max'],sprintf(__('SEO title length is %d characters.','ai-content-studio'),$tl),false,7);$ml=$this->length($d['meta_description']);$check('description_length',$ml>=$profile['description_min']&&$ml<=$profile['description_max'],sprintf(__('Meta description length is %d characters.','ai-content-studio'),$ml),false,7);$check('slug_structure',''!==$d['slug']&&$d['slug']===sanitize_title($d['slug'])&&$this->length($d['slug'])<=$profile['slug_max'],__('Slug is lowercase, hyphenated, and within the recommendation.','ai-content-studio'),true,7);
		foreach(array('title'=>$d['seo_title'],'description'=>$d['meta_description']) as $where=>$text){$required=!empty($settings['keyword']['require_in_'.$where]);$check('keyword_in_'.$where,$this->contains($text,$keyword),sprintf(__('Focus keyword placement in %s.','ai-content-studio'),$where),$required,7);}$slug_phrase=str_replace(' ','-',$keyword);$check('keyword_in_slug',''!==$slug_phrase&&str_contains($d['slug'],$slug_phrase),__('Focus keyword appears in the slug.','ai-content-studio'),!empty($settings['keyword']['require_in_slug']),6);
		$intro=implode(' ',array_slice(preg_split('/\s+/u',$visible,-1,PREG_SPLIT_NO_EMPTY)?:array(),0,150));$check('keyword_in_introduction',$this->contains($intro,$keyword),__('Focus keyword appears in the first 150 visible words.','ai-content-studio'),!empty($settings['keyword']['require_in_introduction']),6);preg_match_all('/<h[23][^>]*>(.*?)<\/h[23]>/is',(string)($article['content']??''),$hm);$heading=implode(' ',array_map('wp_strip_all_tags',$hm[1]??array()));$check('keyword_in_heading',$this->contains($heading,$keyword),__('Focus keyword appears in an H2 or H3.','ai-content-studio'),false,5);
		$check('keyword_density',$density>=(float)$settings['keyword']['density_minimum']&&$density<=(float)$settings['keyword']['density_maximum'],sprintf(__('Keyword occurs %1$d times; approximate phrase density is %2$s%%.','ai-content-studio'),$occ,$density),false,7);$number=(bool)preg_match('/\b\d+\b/u',$d['seo_title']);$power=$this->matched($d['seo_title'],self::POWER);$sentiment=$this->matched($d['seo_title'],array_merge(self::POSITIVE,self::NEGATIVE));$check('title_number','required'!==$settings['title']['use_number']?$settings['title']['use_number']!=='avoid'||!$number:$number,__('Title number preference was evaluated.','ai-content-studio'),false,2);$check('title_power_word',empty($settings['title']['use_power_word'])||''!==$power,__('Power-word preference was evaluated.','ai-content-studio'),false,2);$check('title_sentiment','required'!==$settings['title']['use_sentiment_word']?$settings['title']['use_sentiment_word']!=='avoid'||''===$sentiment:''!==$sentiment,__('Sentiment-word preference was evaluated.','ai-content-studio'),false,2);
		[$internal,$external]=$this->links((string)($article['content']??''));$check('internal_links',!$settings['links']['internal_enabled']||$internal>0,sprintf(__('Existing internal links: %d.','ai-content-studio'),$internal),false,3);$check('external_links',!$settings['links']['external_enabled']||$external>0,sprintf(__('Existing external links: %d.','ai-content-studio'),$external),false,3);$has_image=absint($article['featured_image_attachment_id']??0)>0;$check('featured_image',$has_image,__('Featured image availability was checked.','ai-content-studio'),false,3);$check('image_alt',''!==$d['image_alt_text'],__('Suggested image alt text is available.','ai-content-studio'),false,3);$check('keyword_in_image_alt',$this->contains($d['image_alt_text'],$keyword),__('Focus keyword placement in image alt text was checked.','ai-content-studio'),false,2);$check('word_count',$words>0,sprintf(__('Visible article word count: %d.','ai-content-studio'),$words),true,5);$check('excerpt',''!==$d['excerpt'],__('SEO excerpt is available.','ai-content-studio'),true,4);$check('terms',!empty($d['categories'])&&!empty($d['tags']),__('Suggested categories and tags are available.','ai-content-studio'),false,4);
		$score=$total?max(0,min(100,(int)round(($pass/$total)*100))):0;$label=$score>=90?'Excellent':($score>=75?'Good':($score>=50?'Fair':'Needs Work'));return array('score'=>$score,'label'=>$label,'checks'=>$checks,'passed_checks'=>array_values(array_filter($checks,static fn($c)=>!empty($c['passed']))),'warnings'=>$warnings,'blocking_issues'=>$blocking,'keyword_occurrences'=>$occ,'keyword_density'=>$density,'word_count'=>$words,'internal_link_count'=>$internal,'external_link_count'=>$external,'title_uses_number'=>$number,'title_power_word'=>$power,'title_sentiment_word'=>$sentiment,'profile'=>$target,'profile_note'=>$profile['note'],'introduction_rule'=>'first_150_visible_words');}
	private function visible(string $html):string{return $this->normalize(html_entity_decode(wp_strip_all_tags(strip_shortcodes($html)),ENT_QUOTES|ENT_HTML5,get_bloginfo('charset')?:'UTF-8'));}private function normalize(string $s):string{return trim(preg_replace('/\s+/u',' ',function_exists('mb_strtolower')?mb_strtolower($s,'UTF-8'):strtolower($s))??'');}private function words(string $s):int{return ''===$s?0:count(preg_split('/\s+/u',$s,-1,PREG_SPLIT_NO_EMPTY)?:array());}private function length(string $s):int{return function_exists('mb_strlen')?mb_strlen($s,'UTF-8'):strlen($s);}private function contains(string $text,string $phrase):bool{return ''!==$phrase&&$this->phrase_count($text,$phrase)>0;}private function phrase_count(string $text,string $phrase):int{if(''===$phrase){return 0;}$pattern='/(?<![\pL\pN])'.preg_quote($this->normalize($phrase),'/').'(?![\pL\pN])/iu';return preg_match_all($pattern,$this->normalize($text),$m)?:0;}private function matched(string $text,array $words):string{foreach($words as $w){if($this->phrase_count($text,$w)){return $w;}}return '';}
	private function links(string $html):array{$internal=0;$external=0;$host=strtolower((string)wp_parse_url(home_url('/'),PHP_URL_HOST));if(preg_match_all('/<a\s[^>]*href=["\']([^"\']+)["\']/i',$html,$m)){foreach($m[1] as $url){$url=trim(html_entity_decode($url));if(''===$url||str_starts_with($url,'#')||preg_match('/^(?:mailto|tel|javascript):/i',$url)){continue;}if(str_starts_with($url,'/')&&!str_starts_with($url,'//')){$internal++;continue;}$scheme=wp_parse_url($url,PHP_URL_SCHEME);$h=strtolower((string)wp_parse_url($url,PHP_URL_HOST));if(in_array($scheme,array('http','https'),true)&&$h){$h===$host?$internal++:$external++;}}}return array($internal,$external);}
}
