<?php
/**
 * Automation-run persistence and execution locking.
 *
 * @package AIContentStudio
 */

if ( ! defined( 'ABSPATH' ) ) { exit; }

final class AICS_Automation_Run_Repository {
	private const TRIGGERS=array('scheduled','manual','retry','system');
	private const STATUSES=array('queued','running','retrying','completed','failed','cancelled');
	private const ACTIVE=array('queued','running','retrying');
	private const STEPS=array('pending','generate_ideas','evaluate_ideas','select_ideas','queue_idea','generate_article','validate_article','create_post','generate_featured_image','generate_seo','apply_seo','schedule_post','publish_post','waiting_idea_approval','waiting_article_approval','waiting_publish_approval','finalize','complete');
	private const COLUMNS='id,run_uuid,profile_id,active_profile_key,trigger_type,status,current_step,configuration_snapshot,locked_at,lock_expires_at,attempt_count,max_attempts,next_retry_at,last_error_code,started_at,completed_at,created_at,updated_at';
	private const CONFIG_SECTIONS=array('business_context','content_settings','schedule_settings','workflow_rules','publishing_settings');
	private const CONFIG_KEYS=array('business_context'=>array('business_name','business_description','industry','products_services','target_audience','primary_location','website_purpose','brand_voice','preferred_tone','core_topics','topics_to_avoid','preferred_cta','prohibited_claims'),'content_settings'=>array('ideas_per_cycle','selected_ideas_per_cycle','default_tone','article_length','duplicate_lookback_days','include_faq','allow_tables','allow_lists','idea_instructions','article_instructions','featured_image_instructions'),'schedule_settings'=>array('frequency','interval','days_of_week','publish_time','posts_per_period','start_date','end_date','monthly_day'),'workflow_rules'=>array('require_idea_approval','require_article_approval','require_publish_approval'),'publishing_settings'=>array('publishing_mode','post_status_after_generation','category_id','author_id'));

	/** Creates one queued run, enforcing one active run per profile. */
	public function create_run($profile_id,array $args=array()):array{
		global $wpdb;$profile_id=absint($profile_id);
		if(0===$profile_id||null===(new AICS_Automation_Profile_Repository())->get_by_id($profile_id)){return self::result(false,0,'','invalid_profile');}
		$trigger=self::key($args['trigger_type']??'scheduled');if(!in_array($trigger,self::TRIGGERS,true)){return self::result(false,0,'','invalid_trigger_type');}
		$max=self::strict_int($args['max_attempts']??3,1,10);if(null===$max){return self::result(false,0,'','invalid_max_attempts');}
		$snapshot=is_scalar($args['configuration_snapshot']??null)?(string)$args['configuration_snapshot']:'';if(null===$this->decode_configuration_snapshot(array('configuration_snapshot'=>$snapshot))){return self::result(false,0,'','run_configuration_snapshot_failed');}
		$active=$this->get_active_run_for_profile($profile_id);if(null!==$active){return self::result(false,$active['id'],'','active_run_exists');}
		$uuid=wp_generate_uuid4();if(!is_string($uuid)||!wp_is_uuid($uuid,4)){return self::result(false,0,'','uuid_generation_failed');}
		$now=self::now();$row=array('run_uuid'=>$uuid,'profile_id'=>$profile_id,'active_profile_key'=>$profile_id,'trigger_type'=>$trigger,'status'=>'queued','current_step'=>'pending','configuration_snapshot'=>$snapshot,'lock_token'=>'','locked_at'=>null,'lock_expires_at'=>null,'attempt_count'=>0,'max_attempts'=>$max,'next_retry_at'=>null,'last_error_code'=>'','started_at'=>null,'completed_at'=>null,'created_at'=>$now,'updated_at'=>$now);
		$ok=$wpdb->insert($this->table(),$row,array('%s','%d','%d','%s','%s','%s','%s','%s','%s','%s','%d','%d','%s','%s','%s','%s','%s','%s'));
		if(false===$ok){$active=$this->get_active_run_for_profile($profile_id);return self::result(false,$active['id']??0,'',$active?'active_run_exists':'database_insert_failed');}
		return self::result(true,(int)$wpdb->insert_id,$uuid,'run_created');
	}

	public function get_by_id($run_id):?array{global $wpdb;$sql=$wpdb->prepare("SELECT ".self::COLUMNS." FROM {$this->table()} WHERE id=%d LIMIT 1",absint($run_id));return $this->normalize($wpdb->get_row($sql,ARRAY_A));}
	public function get_by_uuid($uuid):?array{global $wpdb;$uuid=is_scalar($uuid)?sanitize_text_field((string)$uuid):'';if(!wp_is_uuid($uuid)){return null;}$sql=$wpdb->prepare("SELECT ".self::COLUMNS." FROM {$this->table()} WHERE run_uuid=%s LIMIT 1",$uuid);return $this->normalize($wpdb->get_row($sql,ARRAY_A));}
	public function get_active_run_for_profile($profile_id):?array{global $wpdb;$sql=$wpdb->prepare("SELECT ".self::COLUMNS." FROM {$this->table()} WHERE active_profile_key=%d AND status IN ('queued','running','retrying') LIMIT 1",absint($profile_id));return $this->normalize($wpdb->get_row($sql,ARRAY_A));}
	public function get_publish_at(array $run):?string{$raw=$run['configuration_snapshot']??null;if(!is_string($raw)){return null;}$data=json_decode($raw,true);return is_array($data)?self::datetime($data['publish_at']??null):null;}

	public function decode_configuration_snapshot(array $run):?array{$raw=$run['configuration_snapshot']??null;if(!is_string($raw)||''===trim($raw)){return null;}$data=json_decode($raw,true);if(JSON_ERROR_NONE!==json_last_error()||!is_array($data)||1!==($data['snapshot_version']??null)||!in_array($data['mode']??'',array('autopilot','approval'),true)){return null;}$out=array('snapshot_version'=>1,'mode'=>$data['mode']);foreach(self::CONFIG_SECTIONS as $section){if(!isset($data[$section])||!is_array($data[$section])){return null;}$allowed=array_fill_keys(self::CONFIG_KEYS[$section],true);$filtered=array_intersect_key($data[$section],$allowed);if('content_settings'===$section){foreach(array('idea_instructions','article_instructions','featured_image_instructions') as $key){if(!array_key_exists($key,$filtered)){$filtered[$key]='';}}}if(count($filtered)!==count(self::CONFIG_KEYS[$section])){return null;}$out[$section]=$filtered;}$legacy=!isset($data['featured_image_settings']);if(!$legacy){$image=AICS_Automation_Featured_Image_Settings::validate(is_array($data['featured_image_settings'])?$data['featured_image_settings']:array());if(is_wp_error($image)){return null;}$out['featured_image_settings']=$image;}else{$out['featured_image_settings']=AICS_Automation_Featured_Image_Settings::defaults();}$out['featured_image_legacy']=$legacy;$out['seo_legacy']=!isset($data['seo_settings']);$out['seo_settings']=AICS_SEO_Configuration::normalize_stored($data['seo_settings']??array(),false);return $out;}

	public function get_effective_configuration(array $run,?array &$profile=null):array{$snapshot=$this->decode_configuration_snapshot($run);if(null!==$snapshot){unset($snapshot['snapshot_version']);if(is_array($profile)){$profile=array_merge($profile,$snapshot);}return array('success'=>true,'code'=>'run_configuration_loaded','configuration'=>$snapshot,'source'=>'snapshot','legacy_profile_fallback'=>false);}$raw=$run['configuration_snapshot']??null;if(is_string($raw)&&''!==trim($raw)){return array('success'=>false,'code'=>'run_configuration_snapshot_invalid','configuration'=>array(),'source'=>'snapshot','legacy_profile_fallback'=>false);}$profile=$profile??(new AICS_Automation_Profile_Repository())->get_by_id(absint($run['profile_id']??0));if(!$profile){return array('success'=>false,'code'=>'automation_profile_missing','configuration'=>array(),'source'=>'profile_fallback','legacy_profile_fallback'=>true);}$configuration=array('mode'=>$profile['mode']??'autopilot');foreach(self::CONFIG_SECTIONS as $section){$configuration[$section]=is_array($profile[$section]??null)?$profile[$section]:array();}$configuration['featured_image_settings']=AICS_Automation_Featured_Image_Settings::defaults();$configuration['featured_image_legacy']=true;$configuration['seo_settings']=AICS_SEO_Configuration::defaults(false);$configuration['seo_legacy']=true;return array('success'=>true,'code'=>'run_configuration_loaded','configuration'=>$configuration,'source'=>'profile_fallback','legacy_profile_fallback'=>true);}

	/** Finds bounded candidates; claim_run remains the atomic ownership boundary. */
	public function get_claimable_runs($utc_now,array $steps,$limit=1):array{global $wpdb;$now=self::datetime($utc_now);$allowed=array('pending','generate_ideas','evaluate_ideas','queue_idea','generate_article','create_post','generate_featured_image','generate_seo','apply_seo','schedule_post','publish_post','finalize');$steps=array_values(array_intersect(array_unique(array_map(static fn($v)=>self::key($v),array_filter($steps,'is_scalar'))),$allowed));if(null===$now||empty($steps)){return array();}$limit=max(1,min(10,absint($limit)));$marks=implode(',',array_fill(0,count($steps),'%s'));$values=array_merge(array($now,$now),$steps,array($limit));$sql=$wpdb->prepare("SELECT ".self::COLUMNS." FROM {$this->table()} WHERE (status='queued' OR (status='retrying' AND (next_retry_at IS NULL OR next_retry_at<=%s))) AND (lock_token='' OR lock_expires_at IS NULL OR lock_expires_at<=%s) AND attempt_count<max_attempts AND current_step IN ({$marks}) ORDER BY CASE WHEN next_retry_at IS NULL THEN 0 ELSE 1 END ASC,next_retry_at ASC,created_at ASC,id ASC LIMIT %d",$values);return array_values(array_filter(array_map(array($this,'normalize'),$wpdb->get_results($sql,ARRAY_A))));}

	/** Returns a bounded controlled run list without lock tokens. */
	public function get_runs(array $args=array()):array{
		global $wpdb;$where=array('1=1');$values=array();$runs_table=$this->table();
		if(isset($args['profile_id'])){$where[]='profile_id=%d';$values[]=absint($args['profile_id']);}
		if(isset($args['status'])&&in_array($args['status'],self::STATUSES,true)){$where[]='status=%s';$values[]=$args['status'];}
		if(isset($args['current_step'])&&in_array($args['current_step'],self::STEPS,true)){$where[]='current_step=%s';$values[]=$args['current_step'];}
		if(isset($args['trigger_type'])&&in_array($args['trigger_type'],self::TRIGGERS,true)){$where[]='trigger_type=%s';$values[]=$args['trigger_type'];}
		if(isset($args['created_after'])){$date=self::datetime($args['created_after']);$where[]=null===$date?'1=0':'created_at>=%s';if(null!==$date){$values[]=$date;}}
		if(!empty($args['needs_attention'])){$articles=$wpdb->prefix.'aics_articles';$ideas=$wpdb->prefix.'aics_content_ideas';$snapshot=get_option('aics_automation_health_snapshot',array());$health=array_slice(array_values(array_unique(array_filter(array_map('absint',$snapshot['affected_run_ids']??array())))),0,20);$health_sql=$health?' OR '.$runs_table.'.id IN ('.implode(',',$health).')':'';$where[]="((status<>'cancelled' AND status<>'completed' AND (status IN ('retrying','failed') OR last_error_code<>'' OR EXISTS (SELECT 1 FROM {$ideas} i WHERE i.run_id={$runs_table}.id AND i.status='failed') OR EXISTS (SELECT 1 FROM {$articles} a WHERE a.run_id={$runs_table}.id AND (a.status IN ('needs_attention','failed') OR (a.featured_image_required=1 AND a.featured_image_status IN ('failed','needs_attention','retrying')) OR (a.wordpress_post_id IS NOT NULL AND a.wordpress_post_id>0 AND NOT EXISTS (SELECT 1 FROM {$wpdb->posts} p WHERE p.ID=a.wordpress_post_id)))))){$health_sql})";}
		$order='ASC'===strtoupper((string)($args['order']??'DESC'))?'ASC':'DESC';$allowed=array('id','status','created_at','updated_at','next_retry_at');$orderby=in_array($args['orderby']??'',$allowed,true)?$args['orderby']:'id';$limit=max(1,min(100,absint($args['limit']??20)));$offset=absint($args['offset']??0);$values[]=$limit;$values[]=$offset;
		$order_sql=!empty($args['needs_attention'])?"CASE status WHEN 'failed' THEN 0 WHEN 'retrying' THEN 1 ELSE 2 END ASC,updated_at DESC":"{$orderby} {$order}";
		$sql=$wpdb->prepare("SELECT ".self::COLUMNS." FROM {$this->table()} WHERE ".implode(' AND ',$where)." ORDER BY {$order_sql} LIMIT %d OFFSET %d",$values);return array_values(array_filter(array_map(array($this,'normalize'),$wpdb->get_results($sql,ARRAY_A))));
	}

	/** Counts runs through strictly controlled filters. */
	public function count_runs(array $args=array()):int{
		global $wpdb;$where=array('1=1');$values=array();$runs_table=$this->table();
		if(isset($args['profile_id'])){$id=absint($args['profile_id']);$where[]=$id>0?'profile_id=%d':'1=0';if($id>0){$values[]=$id;}}
		if(isset($args['status'])){if(in_array($args['status'],self::STATUSES,true)){$where[]='status=%s';$values[]=$args['status'];}else{$where[]='1=0';}}
		if(isset($args['current_step'])){if(in_array($args['current_step'],self::STEPS,true)){$where[]='current_step=%s';$values[]=$args['current_step'];}else{$where[]='1=0';}}
		if(isset($args['trigger_type'])){if(in_array($args['trigger_type'],self::TRIGGERS,true)){$where[]='trigger_type=%s';$values[]=$args['trigger_type'];}else{$where[]='1=0';}}
		if(isset($args['created_after'])){$date=self::datetime($args['created_after']);$where[]=null===$date?'1=0':'created_at>=%s';if(null!==$date){$values[]=$date;}}
		if(!empty($args['needs_attention'])){$articles=$wpdb->prefix.'aics_articles';$ideas=$wpdb->prefix.'aics_content_ideas';$snapshot=get_option('aics_automation_health_snapshot',array());$health=array_slice(array_values(array_unique(array_filter(array_map('absint',$snapshot['affected_run_ids']??array())))),0,20);$health_sql=$health?' OR '.$runs_table.'.id IN ('.implode(',',$health).')':'';$where[]="((status<>'cancelled' AND status<>'completed' AND (status IN ('retrying','failed') OR last_error_code<>'' OR EXISTS (SELECT 1 FROM {$ideas} i WHERE i.run_id={$runs_table}.id AND i.status='failed') OR EXISTS (SELECT 1 FROM {$articles} a WHERE a.run_id={$runs_table}.id AND (a.status IN ('needs_attention','failed') OR (a.featured_image_required=1 AND a.featured_image_status IN ('failed','needs_attention','retrying')) OR (a.wordpress_post_id IS NOT NULL AND a.wordpress_post_id>0 AND NOT EXISTS (SELECT 1 FROM {$wpdb->posts} p WHERE p.ID=a.wordpress_post_id)))))){$health_sql})";}
		$sql="SELECT COUNT(*) FROM {$runs_table} WHERE ".implode(' AND ',$where);return (int)$wpdb->get_var($values?$wpdb->prepare($sql,$values):$sql);
	}

	public function get_operational_counts():array{global $wpdb;$table=$this->table();$row=$wpdb->get_row("SELECT SUM(status IN ('queued','running','retrying')) active_runs,SUM(status='retrying') retrying_runs,SUM(status='failed') failed_runs,SUM(status='completed') completed_runs FROM {$table}",ARRAY_A);return array('active'=>absint($row['active_runs']??0),'retrying'=>absint($row['retrying_runs']??0),'failed'=>absint($row['failed_runs']??0),'completed'=>absint($row['completed_runs']??0),'needs_attention'=>$this->count_runs(array('needs_attention'=>true)));}

	/** Atomically claims a queued or ready retry run and increments attempts once. */
	public function claim_run($run_id,$lock_ttl=300):array{
		global $wpdb;$id=absint($run_id);$ttl=self::strict_int($lock_ttl,60,3600);if(0===$id){return self::lock_result(false,0,'','run_not_found');}if(null===$ttl){return self::lock_result(false,$id,'','invalid_lock_ttl');}
		$token=wp_generate_password(64,false,false);if(64!==strlen($token)){return self::lock_result(false,$id,'','lock_token_generation_failed');}$now=self::now();$expires=self::plus_seconds($now,$ttl);
		$sql=$wpdb->prepare("UPDATE {$this->table()} SET status='running',lock_token=%s,locked_at=%s,lock_expires_at=%s,attempt_count=attempt_count+1,started_at=COALESCE(started_at,%s),next_retry_at=NULL,updated_at=%s WHERE id=%d AND status IN ('queued','retrying') AND (status='queued' OR next_retry_at IS NULL OR next_retry_at<=%s) AND (lock_token='' OR lock_expires_at IS NULL OR lock_expires_at<=%s) AND attempt_count<max_attempts",$token,$now,$expires,$now,$now,$id,$now,$now);
		$changed=$wpdb->query($sql);if(1===$changed){return self::lock_result(true,$id,$token,'run_claimed');}
		$run=$this->get_by_id($id);if(null===$run){return self::lock_result(false,$id,'','run_not_found');}if($run['attempt_count']>=$run['max_attempts']&&in_array($run['status'],array('queued','retrying'),true)){$this->fail_exhausted($id,$now);return self::lock_result(false,$id,'','retries_exhausted');}if('retrying'===$run['status']&&null!==$run['next_retry_at']&&$run['next_retry_at']>$now){return self::lock_result(false,$id,'','run_not_ready');}if('running'===$run['status']){return self::lock_result(false,$id,'','run_locked');}return self::lock_result(false,$id,'','run_not_claimable');
	}

	public function refresh_lock($run_id,$lock_token,$lock_ttl=300):array{global $wpdb;$id=absint($run_id);$token=is_scalar($lock_token)?(string)$lock_token:'';$ttl=self::strict_int($lock_ttl,60,3600);if(null===$ttl){return self::simple(false,$id,'invalid_lock_ttl');}if(0===$id||''===$token){return self::simple(false,$id,'invalid_lock');}$now=self::now();$expires=self::plus_seconds($now,$ttl);$sql=$wpdb->prepare("UPDATE {$this->table()} SET lock_expires_at=%s,updated_at=%s WHERE id=%d AND status='running' AND lock_token=%s AND lock_expires_at IS NOT NULL AND lock_expires_at>%s",$expires,$now,$id,$token,$now);$changed=$wpdb->query($sql);if(1===$changed){return self::simple(true,$id,'lock_refreshed');}$owned=(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$this->table()} WHERE id=%d AND status='running' AND lock_token=%s AND lock_expires_at>%s",$id,$token,$now));return 1===$owned?self::simple(true,$id,'lock_refreshed'):self::simple(false,$id,null===$this->get_by_id($id)?'run_not_found':'invalid_or_expired_lock');}
	public function release_lock($run_id,$lock_token):array{$now=self::now();return $this->worker_update($run_id,$lock_token,array('status'=>'queued','attempt_count'=>0,'next_retry_at'=>null,'last_error_code'=>'','lock_token'=>'','locked_at'=>null,'lock_expires_at'=>null,'updated_at'=>$now),array('%s','%d','%s','%s','%s','%s','%s','%s'),'lock_released');}
	public function update_step($run_id,$lock_token,$step):array{$step=self::key($step);if(!in_array($step,self::STEPS,true)||'complete'===$step){return self::simple(false,$run_id,'invalid_workflow_step');}return $this->worker_update($run_id,$lock_token,array('current_step'=>$step,'updated_at'=>self::now()),array('%s','%s'),'step_updated');}

	public function schedule_retry($run_id,$lock_token,$error_code,$retry_at):array{
		$run=$this->get_by_id($run_id);$error=self::error($error_code);$retry=self::datetime($retry_at);$now=self::now();if(''===$error){return self::simple(false,$run_id,'invalid_error_code');}if(null===$retry||$retry<=$now){return self::simple(false,$run_id,'invalid_retry_datetime');}if(null===$run){return self::simple(false,$run_id,'run_not_found');}if($run['attempt_count']>=$run['max_attempts']){return $this->mark_failed($run_id,$lock_token,'retries_exhausted');}
		return $this->worker_update($run_id,$lock_token,array('status'=>'retrying','next_retry_at'=>$retry,'last_error_code'=>$error,'lock_token'=>'','locked_at'=>null,'lock_expires_at'=>null,'updated_at'=>$now),array('%s','%s','%s','%s','%s','%s','%s'),'retry_scheduled');
	}

	public function mark_completed($run_id,$lock_token):array{$now=self::now();return $this->worker_update($run_id,$lock_token,array('status'=>'completed','current_step'=>'complete','completed_at'=>$now,'attempt_count'=>0,'lock_token'=>'','locked_at'=>null,'lock_expires_at'=>null,'next_retry_at'=>null,'last_error_code'=>'','active_profile_key'=>null,'updated_at'=>$now),array('%s','%s','%s','%d','%s','%s','%s','%s','%s','%s','%s'),'run_completed');}
	public function validate_finalization(array $run,array $profile):array{$effective=$this->get_effective_configuration($run,$profile);if(empty($effective['success'])){return self::simple(false,$run['id']??0,$effective['code']);}$configuration=$effective['configuration'];$mode=$configuration['publishing_settings']['publishing_mode']??'';$publish_at=$this->get_publish_at($run);if('publish'===$mode&&is_string($publish_at)&&$publish_at>self::now()){$mode='schedule';}if(!in_array($mode,array('draft','schedule','publish'),true)){return self::simple(false,$run['id']??0,'invalid_publishing_mode');}$articles=(new AICS_Article_Repository())->get_articles_for_run(absint($run['id']??0),array('profile_id'=>absint($run['profile_id']??0),'limit'=>100));$articles=array_values(array_filter($articles,static fn($article)=>'rejected'!==$article['status']));if(!$articles){return self::simple(false,$run['id']??0,'run_has_no_articles');}$delivery=new AICS_Automation_Delivery_Service();$posts=0;foreach($articles as $article){$image_guard=(new AICS_Automation_Featured_Image_Service(null))->delivery_allowed($article,is_array($configuration['featured_image_settings']??null)?$configuration['featured_image_settings']:array());if(empty($image_guard['success'])){return self::simple(false,$run['id']??0,$image_guard['code']);}$owned=$delivery->validate_article_post_ownership($article);if(empty($owned['success'])){continue;}++$posts;$status=$owned['post']->post_status;if(!empty($configuration['workflow_rules']['require_publish_approval'])&&in_array($mode,array('schedule','publish'),true)&&'draft'===$status){return self::simple(false,$run['id']??0,'final_publish_approval_not_completed');}$allowed='draft'===$mode?array('draft','future','publish'):('schedule'===$mode?array('future','publish'):array('publish'));if(!in_array($status,$allowed,true)){return self::simple(false,$run['id']??0,'run_not_ready_to_finalize');}}if(0===$posts){return self::simple(false,$run['id']??0,'run_has_no_posts');}if($posts!==count($articles)){return self::simple(false,$run['id']??0,'run_not_ready_to_finalize');}return self::simple(true,$run['id']??0,'run_ready_to_finalize');}
	public function mark_failed($run_id,$lock_token,$error_code):array{$error=self::error($error_code);if(''===$error){return self::simple(false,$run_id,'invalid_error_code');}$now=self::now();return $this->worker_update($run_id,$lock_token,array('status'=>'failed','completed_at'=>$now,'last_error_code'=>$error,'lock_token'=>'','locked_at'=>null,'lock_expires_at'=>null,'next_retry_at'=>null,'active_profile_key'=>null,'updated_at'=>$now),array('%s','%s','%s','%s','%s','%s','%s','%s','%s'),'run_failed');}

	/** Atomically resumes a human-approval waiting step without a worker lock. */
	public function transition_waiting_step($run_id,$expected_step,$next_step):array{global $wpdb;$id=absint($run_id);$expected=self::key($expected_step);$next=self::key($next_step);$pairs=array('waiting_idea_approval'=>array('queue_idea'),'waiting_article_approval'=>array('create_post'),'waiting_publish_approval'=>array('schedule_post','publish_post'));if(0===$id||!isset($pairs[$expected])||!in_array($next,$pairs[$expected],true)){return self::simple(false,$id,'invalid_waiting_transition');}$run=$this->get_by_id($id);if(!$run){return self::simple(false,$id,'run_not_found');}if('queued'===$run['status']&&$next===$run['current_step']){return self::simple(true,$id,'run_already_resumed');}$now=self::now();$sql=$wpdb->prepare("UPDATE {$this->table()} SET current_step=%s,updated_at=%s WHERE id=%d AND status='queued' AND current_step=%s AND lock_token='' AND (lock_expires_at IS NULL OR lock_expires_at<=%s)",$next,$now,$id,$expected,$now);$changed=$wpdb->query($sql);return 1===$changed?self::simple(true,$id,'run_resumed'):self::simple(false,$id,'run_transition_conflict');}

	/** Atomically stops a final-publishing approval run while preserving its drafts. */
	public function cancel_waiting_run($run_id,$expected_step,$reason_code):array{global $wpdb;$id=absint($run_id);$expected=self::key($expected_step);$reason=self::error($reason_code);$reasons=array('manual_review_required','content_needs_changes','publishing_not_approved','timing_not_suitable','keep_as_drafts');if(0===$id||'waiting_publish_approval'!==$expected||!in_array($reason,$reasons,true)){return self::simple(false,$id,'invalid_waiting_cancellation');}$run=$this->get_by_id($id);if(!$run){return self::simple(false,$id,'run_not_found');}if('cancelled'===$run['status']){return self::simple(true,$id,'run_already_cancelled');}$now=self::now();$sql=$wpdb->prepare("UPDATE {$this->table()} SET status='cancelled',completed_at=%s,last_error_code=%s,active_profile_key=NULL,next_retry_at=NULL,lock_token='',locked_at=NULL,lock_expires_at=NULL,updated_at=%s WHERE id=%d AND status='queued' AND current_step=%s AND lock_token='' AND (lock_expires_at IS NULL OR lock_expires_at<=%s)",$now,$reason,$now,$id,$expected,$now);$changed=$wpdb->query($sql);return 1===$changed?self::simple(true,$id,'run_cancelled'):self::simple(false,$id,'run_transition_conflict');}

	/** Atomically fails a waiting approval run when every candidate was rejected. */
	public function fail_waiting_run($run_id,$expected_step,$error_code):array{global $wpdb;$id=absint($run_id);$expected=self::key($expected_step);$error=self::error($error_code);$allowed=array('waiting_idea_approval'=>'all_ideas_rejected','waiting_article_approval'=>'all_articles_rejected');if(0===$id||!isset($allowed[$expected])||$allowed[$expected]!==$error){return self::simple(false,$id,'invalid_waiting_failure');}$run=$this->get_by_id($id);if(!$run){return self::simple(false,$id,'run_not_found');}if('failed'===$run['status']&&$error===$run['last_error_code']){return self::simple(true,$id,$error);}$now=self::now();$sql=$wpdb->prepare("UPDATE {$this->table()} SET status='failed',completed_at=%s,last_error_code=%s,active_profile_key=NULL,next_retry_at=NULL,lock_token='',locked_at=NULL,lock_expires_at=NULL,updated_at=%s WHERE id=%d AND status='queued' AND current_step=%s AND lock_token='' AND (lock_expires_at IS NULL OR lock_expires_at<=%s)",$now,$error,$now,$id,$expected,$now);$changed=$wpdb->query($sql);return 1===$changed?self::simple(true,$id,$error):self::simple(false,$id,'run_transition_conflict');}

	public function mark_cancelled($run_id):array{global $wpdb;$id=absint($run_id);$now=self::now();$sql=$wpdb->prepare("UPDATE {$this->table()} SET status='cancelled',completed_at=%s,lock_token='',locked_at=NULL,lock_expires_at=NULL,next_retry_at=NULL,active_profile_key=NULL,updated_at=%s WHERE id=%d AND status IN ('queued','retrying')",$now,$now,$id);$changed=$wpdb->query($sql);return 1===$changed?self::simple(true,$id,'run_cancelled'):self::simple(false,$id,null===$this->get_by_id($id)?'run_not_found':'run_not_cancellable');}
	public function cancel_claimed_run($run_id,$lock_token,$error_code='profile_not_active'):array{$error=self::error($error_code);if(''===$error){return self::simple(false,$run_id,'invalid_error_code');}$now=self::now();return $this->worker_update($run_id,$lock_token,array('status'=>'cancelled','completed_at'=>$now,'last_error_code'=>$error,'lock_token'=>'','locked_at'=>null,'lock_expires_at'=>null,'next_retry_at'=>null,'active_profile_key'=>null,'updated_at'=>$now),array('%s','%s','%s','%s','%s','%s','%s','%s','%s'),'run_cancelled');}

	/** Recovers bounded stale locks; attempts at their maximum become terminal failures. */
	public function recover_expired_locks($utc_now,$limit=20):array{
		global $wpdb;$now=self::datetime($utc_now);if(null===$now){return array('success'=>false,'recovered'=>0,'failed'=>0,'code'=>'invalid_reference_datetime');}$limit=max(1,min(100,absint($limit)));$sql=$wpdb->prepare("SELECT id,attempt_count,max_attempts FROM {$this->table()} WHERE status='running' AND lock_expires_at IS NOT NULL AND lock_expires_at<=%s ORDER BY lock_expires_at ASC LIMIT %d",$now,$limit);$rows=$wpdb->get_results($sql,ARRAY_A);$recovered=0;$failed=0;
		foreach($rows as $row){$id=absint($row['id']);if(absint($row['attempt_count'])>=absint($row['max_attempts'])){$q=$wpdb->prepare("UPDATE {$this->table()} SET status='failed',lock_token='',locked_at=NULL,lock_expires_at=NULL,next_retry_at=NULL,active_profile_key=NULL,completed_at=%s,last_error_code='retries_exhausted',updated_at=%s WHERE id=%d AND status='running' AND lock_expires_at<=%s",$now,$now,$id,$now);$failed+=1===$wpdb->query($q)?1:0;}else{$q=$wpdb->prepare("UPDATE {$this->table()} SET status='queued',lock_token='',locked_at=NULL,lock_expires_at=NULL,last_error_code='stale_lock_recovered',updated_at=%s WHERE id=%d AND status='running' AND lock_expires_at<=%s",$now,$id,$now);$recovered+=1===$wpdb->query($q)?1:0;}}
		return array('success'=>true,'recovered'=>$recovered,'failed'=>$failed,'code'=>'expired_locks_recovered');
	}

	public function table_exists():bool{global $wpdb;$table=$this->table();return $table===$wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s',$wpdb->esc_like($table)));}
	public function get_health_candidate_runs($utc_now,array $cutoffs,$limit=100):array{global $wpdb;$now=self::datetime($utc_now);$running=self::datetime($cutoffs['running']??null);$queued=self::datetime($cutoffs['queued']??null);$retry=self::datetime($cutoffs['retry']??null);if(!$now||!$running||!$queued||!$retry){return array();}$limit=max(1,min(100,absint($limit)));$steps="'pending','generate_ideas','evaluate_ideas','queue_idea','generate_article','create_post','generate_featured_image','schedule_post','publish_post','finalize'";$sql=$wpdb->prepare("SELECT id,profile_id,active_profile_key,status,current_step,locked_at,lock_expires_at,(lock_token<>'') has_lock_token,attempt_count,max_attempts,next_retry_at,last_error_code,completed_at,created_at,updated_at FROM {$this->table()} WHERE (status='running' AND updated_at<=%s) OR (status='queued' AND current_step IN ({$steps}) AND next_retry_at IS NULL AND updated_at<=%s) OR (status='retrying' AND (next_retry_at IS NULL OR next_retry_at<=%s)) OR (active_profile_key IS NOT NULL AND (active_profile_key<>profile_id OR status IN ('completed','cancelled','failed'))) OR (status='completed' AND (current_step<>'complete' OR completed_at IS NULL)) OR (status IN ('queued','running','retrying') AND current_step NOT IN ({$steps},'waiting_idea_approval','waiting_article_approval','waiting_publish_approval')) ORDER BY updated_at ASC,id ASC LIMIT %d",$running,$queued,$retry,$limit+1);return $wpdb->get_results($sql,ARRAY_A)?:array();}
	public function get_active_run_counts_by_profile($limit=100):array{global $wpdb;$limit=max(1,min(100,absint($limit)));$sql=$wpdb->prepare("SELECT profile_id,COUNT(*) total FROM {$this->table()} WHERE status IN ('queued','running','retrying') GROUP BY profile_id HAVING COUNT(*)>1 ORDER BY total DESC LIMIT %d",$limit);return $wpdb->get_results($sql,ARRAY_A)?:array();}
	public function get_nonterminal_profile_ids(array $profile_ids):array{global $wpdb;$ids=array_slice(array_values(array_unique(array_filter(array_map('absint',$profile_ids)))),0,100);if(!$ids){return array();}$marks=implode(',',array_fill(0,count($ids),'%d'));$sql=$wpdb->prepare("SELECT DISTINCT profile_id FROM {$this->table()} WHERE profile_id IN ({$marks}) AND status IN ('queued','running','retrying')",$ids);return array_map('absint',$wpdb->get_col($sql));}
	public function get_active_runs_with_posts_for_health($limit=100):array{global $wpdb;$limit=max(1,min(100,absint($limit)));$articles=$wpdb->prefix.'aics_articles';$sql=$wpdb->prepare("SELECT r.id,r.profile_id,r.active_profile_key,r.status,r.current_step,r.locked_at,r.lock_expires_at,(r.lock_token<>'') has_lock_token,r.attempt_count,r.max_attempts,r.next_retry_at,r.last_error_code,r.completed_at,r.created_at,r.updated_at FROM {$this->table()} r WHERE r.status IN ('queued','running','retrying','failed') AND EXISTS (SELECT 1 FROM {$articles} a WHERE a.run_id=r.id AND a.wordpress_post_id IS NOT NULL AND a.wordpress_post_id>0) ORDER BY r.updated_at ASC,r.id ASC LIMIT %d",$limit+1);return $wpdb->get_results($sql,ARRAY_A)?:array();}

	/** Loads control state without exposing the lock token. */
	public function get_run_for_control($run_id):?array{global $wpdb;$sql=$wpdb->prepare("SELECT ".self::COLUMNS.",(lock_token<>'') has_lock_token FROM {$this->table()} WHERE id=%d LIMIT 1",absint($run_id));$row=$wpdb->get_row($sql,ARRAY_A);if(!is_array($row)){return null;}$has=!empty($row['has_lock_token']);unset($row['has_lock_token']);$row=$this->normalize($row);if($row){$row['has_lock_token']=$has;}return $row;}

	/** Strict administrator compare-and-swap transition; target values are planner-owned. */
	public function atomic_control_transition(array $run,array $plan):bool{
		global $wpdb;$id=absint($run['id']??0);$action=$plan['action']??'';$status=$plan['status']??'';$step=$plan['step']??'';
		if(0===$id||!in_array($action,array('retry','resume','cancel'),true)||!in_array($status,array('queued','cancelled'),true)||!in_array($step,self::STEPS,true)){return false;}
		$now=self::now();$sets=array('status=%s','current_step=%s','next_retry_at=NULL',"lock_token=''",'locked_at=NULL','lock_expires_at=NULL','updated_at=%s');$values=array($status,$step,$now);
		if('cancel'===$action){$sets[]='completed_at=COALESCE(completed_at,%s)';$values[]=$now;$sets[]='active_profile_key=NULL';}
		else{$sets[]='completed_at=NULL';$sets[]='active_profile_key=profile_id';if(!empty($plan['reset_attempts'])){$sets[]='attempt_count=0';}}
		$values[]= $id;$values[]=(string)$run['status'];$values[]=(string)$run['current_step'];$values[]=(string)$run['updated_at'];$values[]=$now;
		$profile_guard='cancel'===$action?'':" AND NOT EXISTS (SELECT 1 FROM (SELECT id FROM {$this->table()} WHERE active_profile_key=".$this->table().".profile_id AND id<>%d LIMIT 1) aics_other_active)";
		if('cancel'!==$action){$values[]= $id;}
		$sql=$wpdb->prepare("UPDATE {$this->table()} SET ".implode(',',$sets)." WHERE id=%d AND status=%s AND current_step=%s AND updated_at=%s AND (lock_token='' OR lock_expires_at IS NULL OR lock_expires_at<=%s)".$profile_guard,$values);
		return 1===$wpdb->query($sql);
	}

	private function worker_update($run_id,$token,array $data,array $formats,string $code):array{global $wpdb;$id=absint($run_id);$token=is_scalar($token)?(string)$token:'';if(0===$id||''===$token){return self::simple(false,$id,'invalid_lock');}$now=self::now();$sets=array();$values=array();$i=0;foreach($data as $field=>$value){if(null===$value){$sets[]="{$field}=NULL";}else{$sets[]="{$field}=".$formats[$i];$values[]=$value;}$i++;}$values[]=$id;$values[]=$token;$values[]=$now;$sql=$wpdb->prepare("UPDATE {$this->table()} SET ".implode(',',$sets)." WHERE id=%d AND status='running' AND lock_token=%s AND lock_expires_at IS NOT NULL AND lock_expires_at>%s",$values);$changed=$wpdb->query($sql);return 1===$changed?self::simple(true,$id,$code):self::simple(false,$id,null===$this->get_by_id($id)?'run_not_found':'invalid_or_expired_lock');}
	private function fail_exhausted(int $id,string $now):void{global $wpdb;$sql=$wpdb->prepare("UPDATE {$this->table()} SET status='failed',active_profile_key=NULL,last_error_code='retries_exhausted',completed_at=%s,lock_token='',locked_at=NULL,lock_expires_at=NULL,next_retry_at=NULL,updated_at=%s WHERE id=%d AND status IN ('queued','retrying') AND attempt_count>=max_attempts",$now,$now,$id);$wpdb->query($sql);}
	private function normalize($row):?array{if(!is_array($row)){return null;}foreach(array('id','profile_id','attempt_count','max_attempts') as $f){$row[$f]=absint($row[$f]??0);}$row['active_profile_key']=null===$row['active_profile_key']?null:absint($row['active_profile_key']);$row['trigger_type']=in_array($row['trigger_type']??'',self::TRIGGERS,true)?$row['trigger_type']:'scheduled';$row['status']=in_array($row['status']??'',self::STATUSES,true)?$row['status']:'failed';$row['current_step']=in_array($row['current_step']??'',self::STEPS,true)?$row['current_step']:'pending';foreach(array('locked_at','lock_expires_at','next_retry_at','started_at','completed_at') as $f){$row[$f]=self::datetime($row[$f]??null);}unset($row['lock_token']);return $row;}
	private function table():string{global $wpdb;return $wpdb->prefix.'aics_automation_runs';}
	private static function result(bool $success,int $id,string $uuid,string $code):array{return array('success'=>$success,'run_id'=>$id,'uuid'=>$uuid,'code'=>$code);}
	private static function lock_result(bool $success,int $id,string $token,string $code):array{return array('success'=>$success,'run_id'=>$id,'lock_token'=>$token,'code'=>$code);}
	private static function simple(bool $success,$id,string $code):array{return array('success'=>$success,'run_id'=>absint($id),'code'=>$code);}
	private static function now():string{return current_time('mysql',true);}
	private static function plus_seconds(string $utc,int $seconds):string{return (new DateTimeImmutable($utc,new DateTimeZone('UTC')))->modify('+'.$seconds.' seconds')->format('Y-m-d H:i:s');}
	private static function datetime($v):?string{if(null===$v||''===$v){return null;}if(!is_scalar($v)){return null;}$v=(string)$v;$d=DateTimeImmutable::createFromFormat('!Y-m-d H:i:s',$v,new DateTimeZone('UTC'));$e=DateTimeImmutable::getLastErrors();return false!==$d&&(false===$e||(0===$e['warning_count']&&0===$e['error_count']))&&$d->format('Y-m-d H:i:s')===$v?$v:null;}
	private static function key($v):string{return sanitize_key(is_scalar($v)?(string)$v:'');}
	private static function error($v):string{return substr(self::key($v),0,100);}
	private static function strict_int($v,int $min,int $max):?int{if(!is_scalar($v)||!preg_match('/^\d+$/',(string)$v)){return null;}$v=(int)$v;return $v>=$min&&$v<=$max?$v:null;}
}
