<?php
/** Read-only automation run inspection. @package AIContentStudio */
if(!defined('ABSPATH')){exit;}
final class AICS_Automation_Run_Inspector{
	private AICS_Automation_Run_Repository $runs;private AICS_Automation_Profile_Repository $profiles;private AICS_Content_Idea_Repository $ideas;private AICS_Article_Repository $articles;
	public function __construct(){ $this->runs=new AICS_Automation_Run_Repository();$this->profiles=new AICS_Automation_Profile_Repository();$this->ideas=new AICS_Content_Idea_Repository();$this->articles=new AICS_Article_Repository(); }
	public function counts():array{return $this->runs->get_operational_counts();}
	public function list_runs(array $args):array{$rows=$this->runs->get_runs($args);$ids=array_column($rows,'id');$ideas=$this->ideas->count_for_run_ids($ids);$articles=$this->articles->aggregate_for_run_ids($ids);$out=array();foreach($rows as $run){$profile=$this->profiles->get_by_id($run['profile_id']);$out[]=array('run'=>$run,'profile_name'=>$profile['profile_name']??__('Deleted or Missing Profile','ai-content-studio'),'ideas'=>absint($ideas[$run['id']]??0),'articles'=>absint($articles[$run['id']]['articles']??0),'posts'=>absint($articles[$run['id']]['posts']??0),'problem'=>$this->problem($run));}return $out;}
	public function inspect($run_id):array{$run=$this->runs->get_by_id(absint($run_id));if(!$run){return array('success'=>false,'code'=>'run_not_found');}$profile=$this->profiles->get_by_id($run['profile_id']);$effective=$this->runs->get_effective_configuration($run,$profile);$ideas=$this->ideas->get_ideas_for_run($run['id'],array('limit'=>100,'orderby'=>'created_at','order'=>'ASC'));$articles=$this->articles->get_articles_for_run($run['id'],array('limit'=>100,'orderby'=>'created_at','order'=>'ASC'));foreach($articles as &$article){$post_id=absint($article['wordpress_post_id']);$post=$post_id?get_post($post_id):null;$article['post_info']=array('expected'=>$post_id>0,'missing'=>$post_id>0&&!$post,'id'=>$post_id,'status'=>$post instanceof WP_Post?$post->post_status:'','edit_url'=>$post instanceof WP_Post&&current_user_can('edit_post',$post_id)?get_edit_post_link($post_id,'raw'):'');}unset($article);return array('success'=>true,'run'=>$run,'profile_name'=>$profile['profile_name']??__('Deleted or Missing Profile','ai-content-studio'),'configuration'=>$effective['configuration']??array(),'configuration_source'=>$effective['source']??'profile_fallback','configuration_success'=>!empty($effective['success']),'ideas'=>$ideas,'articles'=>$articles,'problem'=>$this->problem($run,$articles));}
	public function status_label(string $v):string{return $this->label($v,array('queued'=>'Queued','running'=>'Running','retrying'=>'Retrying','completed'=>'Completed','failed'=>'Failed','cancelled'=>'Cancelled'));}
	public function step_label(string $v):string{return $this->label($v,array('pending'=>'Pending','generate_ideas'=>'Generating Ideas','evaluate_ideas'=>'Evaluating Ideas','select_ideas'=>'Selecting Ideas','waiting_idea_approval'=>'Waiting for Idea Approval','queue_idea'=>'Preparing Articles','generate_article'=>'Generating Articles','validate_article'=>'Validating Articles','waiting_article_approval'=>'Waiting for Article Approval','create_post'=>'Creating WordPress Posts','waiting_publish_approval'=>'Waiting for Publishing Approval','schedule_post'=>'Scheduling Posts','publish_post'=>'Publishing Posts','finalize'=>'Finalizing Cycle','complete'=>'Complete'),__('Unknown Step','ai-content-studio'));}
	public function trigger_label(string $v):string{return $this->label($v,array('scheduled'=>'Scheduled','manual'=>'Manual','retry'=>'Retry','system'=>'System'));}
	public function error_label(string $v):string{$map=array('unsafe_script_element'=>'Generated content contained an unsafe script element.','unsafe_style_element'=>'Generated content contained an unsafe style element.','unsafe_embedded_content'=>'Generated content contained unsafe embedded content.','unsafe_form_element'=>'Generated content contained an unsafe form element.','unsafe_event_handler'=>'Generated content contained an unsafe HTML event attribute.','unsafe_url_scheme'=>'Generated content contained an unsafe link.','unsafe_svg_content'=>'Generated content contained unsafe SVG.','unsafe_active_markup'=>'Generated content contained unsafe active markup.','article_content_too_short'=>'Generated content did not meet the minimum content length.','article_content_empty_after_sanitization'=>'Generated content became empty after safety filtering.','article_contains_placeholder_text'=>'Generated content contained placeholder text.','provider_request_failed'=>'The AI provider request failed.','invalid_article_json'=>'The provider returned invalid article data.','article_persistence_failed'=>'The article could not be stored.','article_transition_failed'=>'The article workflow could not advance.','wordpress_post_creation_failed'=>'The WordPress post could not be created.','wordpress_post_ownership_conflict'=>'WordPress post ownership could not be verified.','no_future_publishing_slot'=>'No future publishing time is available.','wordpress_schedule_failed'=>'The WordPress post could not be scheduled.','wordpress_publish_failed'=>'The WordPress post could not be published.','all_ideas_rejected'=>'All ideas were rejected.','all_articles_rejected'=>'All articles were rejected.','retries_exhausted'=>'The retry limit was reached.','run_not_ready_to_finalize'=>'The run is not ready to complete.','run_has_no_articles'=>'The run has no articles.','run_has_no_posts'=>'The run has no WordPress posts.','final_publish_approval_not_completed'=>'Final publishing approval is incomplete.','run_configuration_snapshot_failed'=>'The saved run configuration could not be created.');return ''===$v?__('None','ai-content-studio'):__( $map[$v]??'An internal workflow error occurred.','ai-content-studio');}
	private function problem(array $run,array $articles=array()):string{if('failed'===$run['status']){return $this->error_label($run['last_error_code']);}if('retrying'===$run['status']){return $this->error_label($run['last_error_code']);}foreach($articles as $a){if(in_array($a['status'],array('needs_attention','failed'),true)){return $this->error_label($a['last_error_code']);}if(!empty($a['post_info']['missing'])){return __('A stored WordPress post is missing.','ai-content-studio');}}return ''!==($run['last_error_code']??'')?$this->error_label($run['last_error_code']):__('Content requires review.','ai-content-studio');}
	private function label(string $value,array $map,string $fallback=''):string{$fallback=$fallback?:__('Unknown','ai-content-studio');return __($map[$value]??$fallback,'ai-content-studio');}
}
