<?php
if(!defined('ABSPATH')){exit;}
abstract class AICS_Abstract_Postmeta_SEO_Adapter implements AICS_SEO_Adapter_Interface{
	abstract protected function metadata_keys():array;
	public function validate_data(AICS_SEO_Data $data){$v=$data->to_adapter_data();return ''!==$v['seo_title']&&''!==$v['meta_description']&&''!==$v['focus_keyword']?true:new WP_Error('seo_data_incomplete');}
	public function apply_to_post(int $post_id,AICS_SEO_Data $data){if(!$this->is_available()){return new WP_Error('seo_target_plugin_unavailable');}if(!$this->owned($post_id)){return new WP_Error('seo_post_ownership_invalid');}$valid=$this->validate_data($data);if(is_wp_error($valid)){return $valid;}$v=$data->to_adapter_data();$applied=array();foreach($this->metadata_keys() as $field=>$key){if(''!==$key&&update_post_meta($post_id,$key,$v[$field]??'')!==false){$applied[]=$field;}}$refresh=$this->refresh_post_seo_data($post_id);$verified=$this->verify_application($post_id,$data);if(is_wp_error($verified)){return $verified;}return AICS_SEO_Application_Result::success(array('adapter_key'=>$this->get_key(),'adapter_label'=>$this->get_label(),'post_id'=>$post_id,'applied_fields'=>$applied,'verified_fields'=>$verified,'plugin_applied'=>true,'verification_passed'=>true,'refresh_requested'=>true,'warnings'=>is_wp_error($refresh)?array('seo_plugin_refresh_failed'):array(),'applied_at'=>current_time('mysql',true)));}
	public function read_from_post(int $post_id){if(!$this->owned($post_id)){return new WP_Error('seo_post_ownership_invalid');}$out=array();foreach($this->metadata_keys() as $field=>$key){$out[$field]=''===$key?'':$this->normalize_comparison_value((string)get_post_meta($post_id,$key,true),$field);}return $out;}
	public function verify_application(int $post_id,AICS_SEO_Data $data){$read=$this->read_from_post($post_id);if(is_wp_error($read)){return $read;}$expected=$data->to_adapter_data();$ok=array();foreach($this->metadata_keys() as $field=>$key){if(''===$key){continue;}if(($read[$field]??'')!==$this->normalize_comparison_value((string)($expected[$field]??''),$field)){return new WP_Error('seo_adapter_verification_failed');}$ok[]=$field;}return $ok;}
	public function supports_focus_keyword():bool{return ''!==($this->metadata_keys()['focus_keyword']??'');}public function supports_seo_title():bool{return true;}public function supports_meta_description():bool{return true;}public function supports_score_reading():bool{return false;}
	protected function owned(int $post_id):bool{$post=get_post($post_id);return $post&&'post'===$post->post_type&&1===absint(get_post_meta($post_id,'_aics_generated_post',true))&&absint(get_post_meta($post_id,'_aics_article_id',true))>0;}
	protected function normalize_comparison_value(string $value,string $field):string{$value=wp_unslash(html_entity_decode($value,ENT_QUOTES|ENT_HTML5,get_bloginfo('charset')?:'UTF-8'));return trim(preg_replace('/\s+/u',' ',sanitize_text_field($value))??'');}
}
