<?php
/** Manual Studio facade over the shared featured-image pipeline. @package AIContentStudio */
if ( ! defined( 'ABSPATH' ) ) { exit; }

final class AICS_Manual_Featured_Image_Service {
	private AICS_Manual_Article_Persistence_Service $manual;private AICS_Article_Repository $articles;private AICS_Featured_Image_Ownership_Service $ownership;private AICS_Featured_Image_Pipeline_Service $pipeline;
	public function __construct(?AICS_Manual_Article_Persistence_Service $manual=null,?AICS_Article_Repository $articles=null,?AICS_Featured_Image_Ownership_Service $ownership=null,?AICS_Featured_Image_Pipeline_Service $pipeline=null){$this->manual=$manual??new AICS_Manual_Article_Persistence_Service();$this->articles=$articles??new AICS_Article_Repository();$this->ownership=$ownership??new AICS_Featured_Image_Ownership_Service();$this->pipeline=$pipeline??new AICS_Featured_Image_Pipeline_Service();}

	public function view($article_id,$user_id):array{$loaded=$this->manual->load($article_id,$user_id);if(empty($loaded['success'])){return $this->result(false,$loaded['code']);}$article=$loaded['article'];$post=$this->ownership->validate_post($article);$settings=AICS_Featured_Image_Settings::get_effective();$provider=AICS_Image_Provider_Factory::create($settings['provider']);$configured=is_wp_error($provider)?array('success'=>false):$provider->validate_configuration();if(''===trim((string)($article['featured_image_prompt']??''))){$built=$this->build_prompt($article,$user_id,$settings);if(!is_wp_error($built)){$saved=$this->articles->update_featured_image_prompt($article['id'],$built,$user_id);if(!empty($saved['success'])){$article=$this->articles->get_by_id($article['id']);}}}$data=array('success'=>true,'code'=>'manual_featured_image_ready','article'=>$article,'image_prompt'=>(string)($article['featured_image_prompt']??''),'post_valid'=>!empty($post['success']),'post_code'=>$post['code']??'featured_image_post_invalid','provider_ready'=>!empty($configured['success']),'attachment'=>null);
		$attachment=absint($article['featured_image_attachment_id']);if($attachment){$owned=$this->ownership->validate_attachment($attachment,$article);if(!empty($owned['success'])){$meta=wp_get_attachment_metadata($attachment);$data['attachment']=array('id'=>$attachment,'url'=>(string)wp_get_attachment_image_url($attachment,'medium'),'width'=>absint(is_array($meta)?($meta['width']??0):0),'height'=>absint(is_array($meta)?($meta['height']??0):0),'mime'=>(string)get_post_mime_type($attachment),'alt'=>(string)get_post_meta($attachment,'_wp_attachment_image_alt',true));}else{$data['attachment_error']=$owned['code'];}}
		return $data;}

	public function generate($article_id,$user_id,$prompt=''):array{$view=$this->view($article_id,$user_id);if(empty($view['success'])){return $view;}if(empty($view['post_valid'])){return $this->result(false,'manual_featured_image_post_required');}$post=$view['article']['wordpress_post_id'];if(!user_can(absint($user_id),'edit_post',$post)){return $this->result(false,'manual_featured_image_not_allowed');}$saved=$this->save_prompt($article_id,$user_id,$prompt,false);if(empty($saved['success'])){return $saved;}$view=$this->view($article_id,$user_id);$status=$view['article']['featured_image_status'];if(in_array($status,array('pending','generating'),true)){return $this->result(false,'manual_featured_image_in_progress');}if('skipped'===$status){return $this->result(false,'manual_featured_image_skipped');}$assignment_only=in_array($status,array('uploaded','attached','retrying'),true)&&is_array($view['attachment']);if(empty($view['provider_ready'])&&!$assignment_only){return $this->result(false,'image_provider_not_configured');}
		$result=$this->pipeline->run($view['article']['id'],absint($user_id),false);$message=!empty($result['success'])&&!empty($result['reused'])&&'featured_image_pipeline_succeeded'===($result['code']??'')?__('Featured image assignment completed using the existing Media Library attachment.','ai-content-studio'):$this->message($result['code'],$result['success']);return array_merge($result,array('message'=>$message));}

	public function save_prompt($article_id,$user_id,$value,bool $refresh=false):array{$loaded=$this->manual->load($article_id,$user_id);if(empty($loaded['success'])){return $this->result(false,$loaded['code']);}$article=$loaded['article'];if(!user_can(absint($user_id),'edit_post',absint($article['wordpress_post_id']))){return $this->result(false,'manual_featured_image_not_allowed');}$prompt=$refresh?$this->build_prompt($article,$user_id,AICS_Featured_Image_Settings::get_effective()):AICS_Featured_Image_Prompt_Builder::sanitize_final_prompt($value);if(is_wp_error($prompt)){return $this->result(false,$prompt->get_error_code());}$saved=$this->articles->update_featured_image_prompt($article['id'],$prompt,$user_id);return empty($saved['success'])?$this->result(false,$saved['code']):array('success'=>true,'code'=>'featured_image_prompt_updated','message'=>$refresh?__('Featured image prompt refreshed from the current article.','ai-content-studio'):__('Featured image prompt saved.','ai-content-studio'),'prompt'=>$prompt);}

	private function build_prompt(array $article,int $user,array $settings){$state=new AICS_Manual_Wizard_State_Service($user);$idea=$state->selected_idea();$context=$state->context();return (new AICS_Featured_Image_Prompt_Builder())->build(array('title'=>$article['title'],'excerpt'=>$article['excerpt'],'content'=>$article['content'],'primary_keyword'=>$idea['primary_keyword']??$context['topic_keyword'],'seo_focus_keyword'=>$article['seo_focus_keyword'],'featured_image_instructions'=>$context['featured_image_instructions'],'aspect_ratio'=>$settings['aspect_ratio'],'visual_style'=>$settings['visual_style']));}

	public function save_alt_text($article_id,$user_id,$value):array{$view=$this->view($article_id,$user_id);if(empty($view['success'])){return $view;}if(empty($view['post_valid'])||!user_can(absint($user_id),'edit_post',$view['article']['wordpress_post_id'])){return $this->result(false,'manual_featured_image_not_allowed');}if(!is_array($view['attachment'])){return $this->result(false,$view['attachment_error']??'featured_image_attachment_missing');}$alt=is_scalar($value)?trim(preg_replace('/\s+/u',' ',wp_strip_all_tags((string)$value,true))??''):'';if(''===$alt){$alt=sprintf(__('Featured image for %s','ai-content-studio'),sanitize_text_field((string)$view['article']['title']));}$alt=function_exists('mb_substr')?mb_substr($alt,0,250,'UTF-8'):substr($alt,0,250);$attachment=$view['attachment']['id'];$old=(string)get_post_meta($attachment,'_wp_attachment_image_alt',true);update_post_meta($attachment,'_wp_attachment_image_alt',$alt);if((string)get_post_meta($attachment,'_wp_attachment_image_alt',true)!==$alt){return $this->result(false,'attachment_persistence_failed');}$saved=$this->articles->update_featured_image_alt_text($view['article']['id'],$attachment,$alt,absint($user_id));if(empty($saved['success'])){update_post_meta($attachment,'_wp_attachment_image_alt',$old);return $this->result(false,'attachment_persistence_failed');}return array('success'=>true,'code'=>'manual_featured_image_alt_updated','message'=>__('Image alt text updated.','ai-content-studio'),'article_id'=>$view['article']['id'],'attachment_id'=>$attachment,'alt_text'=>$alt);}

	private function result(bool $success,string $code):array{return array('success'=>$success,'code'=>sanitize_key($code),'message'=>$this->message($code,$success));}
	private function message(string $code,bool $success):string{$messages=array('manual_featured_image_post_required'=>__('Create a WordPress draft before generating a featured image.','ai-content-studio'),'manual_featured_image_not_allowed'=>__('You are not allowed to change this article featured image.','ai-content-studio'),'manual_featured_image_in_progress'=>__('Featured-image generation is already in progress.','ai-content-studio'),'manual_featured_image_skipped'=>__('Featured-image generation was skipped for this article.','ai-content-studio'),'image_provider_not_configured'=>__('The configured image provider is not ready.','ai-content-studio'),'featured_image_ownership_conflict'=>__('This image is associated with another article.','ai-content-studio'),'featured_image_assignment_failed'=>__('The image could not be assigned to this post.','ai-content-studio'),'featured_image_pipeline_succeeded'=>__('Featured image generated and assigned successfully.','ai-content-studio'),'featured_image_already_attached'=>__('The existing featured image is already assigned.','ai-content-studio'));return $messages[$code]??($success?__('Featured-image operation completed.','ai-content-studio'):__('This article featured image requires manual review.','ai-content-studio'));}
}
