<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
final class AICS_SEO_Configuration {
	public static function defaults(bool $enabled=false):array{return array('enabled'=>$enabled,'target_plugin'=>'auto','instructions'=>'','focus_keyword_mode'=>'generate','title'=>array('use_number'=>'optional','use_power_word'=>true,'use_sentiment_word'=>'optional'),'links'=>array('internal_enabled'=>true,'internal_maximum'=>3,'external_enabled'=>true,'external_maximum'=>2),'keyword'=>array('density_minimum'=>0.5,'density_maximum'=>1.5,'require_in_title'=>true,'require_in_description'=>true,'require_in_slug'=>true,'require_in_introduction'=>true,'require_in_heading'=>true,'require_in_image_alt'=>true),'content_image'=>array('enabled'=>true,'source'=>'featured_image','placement'=>'after_introduction'));
	}
	public static function normalize_stored($value,bool $legacy_enabled=false):array{$r=self::validate(is_array($value)?$value:array(),$legacy_enabled);return is_wp_error($r)?self::defaults($legacy_enabled):$r;}
	public static function validate(array $v,bool $default_enabled=false){$d=self::defaults($default_enabled);$target=sanitize_key((string)($v['target_plugin']??$d['target_plugin']));$number=sanitize_key((string)($v['title']['use_number']??$d['title']['use_number']));$sentiment=sanitize_key((string)($v['title']['use_sentiment_word']??$d['title']['use_sentiment_word']));$placement=sanitize_key((string)($v['content_image']['placement']??$d['content_image']['placement']));if(!in_array($target,array('auto','native','yoast','rank_math','aioseo'),true)){return new WP_Error('invalid_seo_target_plugin');}if(!in_array($number,array('optional','required','avoid'),true)||!in_array($sentiment,array('optional','required','avoid'),true)){return new WP_Error('invalid_seo_title_rules');}if(!in_array($placement,array('disabled','after_introduction','before_first_h2','after_first_h2','middle'),true)){return new WP_Error('invalid_seo_image_placement');}$integer=static function($x){return is_scalar($x)&&preg_match('/^\d+$/',(string)$x)?(int)$x:null;};$imax=$integer($v['links']['internal_maximum']??3);$emax=$integer($v['links']['external_maximum']??2);if(null===$imax||$imax>10||null===$emax||$emax>10){return new WP_Error('invalid_seo_link_limits');}$min=filter_var($v['keyword']['density_minimum']??0.5,FILTER_VALIDATE_FLOAT);$max=filter_var($v['keyword']['density_maximum']??1.5,FILTER_VALIDATE_FLOAT);if(false===$min||false===$max||$min<0||$max>5||$min>$max){return new WP_Error('invalid_seo_density_range');}$bool=static fn($x):bool=>in_array($x,array(true,1,'1','true','on'),true);$instructions=substr(sanitize_textarea_field((string)($v['instructions']??'')),0,3000);return array('enabled'=>$bool($v['enabled']??$default_enabled),'target_plugin'=>$target,'instructions'=>$instructions,'focus_keyword_mode'=>'generate','title'=>array('use_number'=>$number,'use_power_word'=>$bool($v['title']['use_power_word']??true),'use_sentiment_word'=>$sentiment),'links'=>array('internal_enabled'=>$bool($v['links']['internal_enabled']??true),'internal_maximum'=>$imax,'external_enabled'=>$bool($v['links']['external_enabled']??true),'external_maximum'=>$emax),'keyword'=>array('density_minimum'=>(float)$min,'density_maximum'=>(float)$max,'require_in_title'=>$bool($v['keyword']['require_in_title']??true),'require_in_description'=>$bool($v['keyword']['require_in_description']??true),'require_in_slug'=>$bool($v['keyword']['require_in_slug']??true),'require_in_introduction'=>$bool($v['keyword']['require_in_introduction']??true),'require_in_heading'=>$bool($v['keyword']['require_in_heading']??true),'require_in_image_alt'=>$bool($v['keyword']['require_in_image_alt']??true)),'content_image'=>array('enabled'=>'disabled'!==$placement&&$bool($v['content_image']['enabled']??true),'source'=>'featured_image','placement'=>$placement));}
	public static function target_labels():array{return array('auto'=>__('Auto-detect','ai-content-studio'),'native'=>__('Native WordPress','ai-content-studio'),'yoast'=>__('Yoast SEO','ai-content-studio'),'rank_math'=>__('Rank Math','ai-content-studio'),'aioseo'=>__('All in One SEO','ai-content-studio'));}
}
