<?php
/** Bounded, prepared Content History queries. @package AIContentStudio */
if(!defined('ABSPATH')){exit;}
final class AICS_Content_History_Query_Service{
	public const PER_PAGE=10;private const STATUSES=array('all','draft','publish','future','pending');private const SOURCES=array('all','manual','automation');
	public function normalize(array $input):array{$status=sanitize_key((string)($input['content_status']??'all'));$source=sanitize_key((string)($input['content_source']??'all'));$search=preg_replace('/\s+/u',' ',trim(sanitize_text_field((string)($input['content_search']??''))))??'';$search=function_exists('mb_substr')?mb_substr($search,0,100):substr($search,0,100);$author=absint($input['content_author']??0);if($author&&!get_userdata($author)){$author=0;}$from=$this->date($input['date_from']??'');$to=$this->date($input['date_to']??'');$error='';if(false===$from||false===$to){$error=__('Enter valid Created From and Created To dates.','ai-content-studio');$from=false===$from?'':$from;$to=false===$to?'':$to;}elseif($from&&$to&&$from>$to){$error=__('Created From cannot be later than Created To.','ai-content-studio');}$page=max(1,min(10000,absint($input['paged']??1)));return array('content_search'=>$search,'content_status'=>in_array($status,self::STATUSES,true)?$status:'all','content_author'=>$author,'date_from'=>$from,'date_to'=>$to,'content_source'=>in_array($source,self::SOURCES,true)?$source:'all','paged'=>$page,'error'=>$error);}
	public function query(array $filters):array{global $wpdb;$f=$this->normalize($filters);if($f['error']){return array('items'=>array(),'total'=>0,'pages'=>0,'page'=>1,'filters'=>$f,'error'=>$f['error']);}$posts=$wpdb->posts;$users=$wpdb->users;$articles=$wpdb->prefix.'aics_articles';$where=array("p.post_type='post'","p.post_status IN ('draft','publish','future','pending')","EXISTS (SELECT 1 FROM {$wpdb->postmeta} pm WHERE pm.post_id=p.ID AND pm.meta_key='_aics_generated_post' AND pm.meta_value='1')");$values=array();if('all'!==$f['content_status']){$where[]='p.post_status=%s';$values[]=$f['content_status'];}if($f['content_author']){$where[]='p.post_author=%d';$values[]=$f['content_author'];}if($f['date_from']){$where[]='p.post_date>=%s';$values[]=$f['date_from'].' 00:00:00';}if($f['date_to']){$where[]='p.post_date<=%s';$values[]=$f['date_to'].' 23:59:59';}if('all'!==$f['content_source']){$where[]='a.source_type=%s';$values[]=$f['content_source'];}$term=$f['content_search'];if(''!==$term){if(ctype_digit($term)){$values[]=absint($term);$values[]=absint($term);$where[]='(p.ID=%d OR a.id=%d OR '.$this->like_sql($wpdb,$term,$values).')';}elseif((function_exists('mb_strlen')?mb_strlen($term):strlen($term))>=2){$where[]='('.$this->like_sql($wpdb,$term,$values).')';}}
		$from="FROM {$posts} p LEFT JOIN {$users} u ON u.ID=p.post_author LEFT JOIN {$articles} a ON a.wordpress_post_id=p.ID WHERE ".implode(' AND ',$where);$count="SELECT COUNT(DISTINCT p.ID) {$from}";$total=(int)$wpdb->get_var($values?$wpdb->prepare($count,$values):$count);$pages=(int)ceil($total/self::PER_PAGE);$page=$pages?min($f['paged'],$pages):1;$query_values=$values;$query_values[]=self::PER_PAGE;$query_values[]=($page-1)*self::PER_PAGE;$sql="SELECT p.ID,p.post_title,p.post_excerpt,p.post_status,p.post_author,p.post_date,p.post_name,u.display_name,u.user_login,a.id article_id,a.source_type,a.title article_title,a.excerpt article_excerpt,a.seo_title,a.seo_meta_description,a.seo_focus_keyword,a.seo_slug,a.run_id {$from} ORDER BY p.post_date DESC,p.ID DESC LIMIT %d OFFSET %d";$rows=$wpdb->get_results($wpdb->prepare($sql,$query_values),ARRAY_A)?:array();return array('items'=>$rows,'total'=>$total,'pages'=>$pages,'page'=>$page,'filters'=>$f,'error'=>'');}
	private function like_sql($wpdb,string $term,array &$values):string{$like='%'.$wpdb->esc_like($term).'%';for($i=0;$i<12;$i++){$values[]=$like;}return "p.post_title LIKE %s OR p.post_excerpt LIKE %s OR p.post_content LIKE %s OR p.post_name LIKE %s OR a.title LIKE %s OR a.excerpt LIKE %s OR a.seo_title LIKE %s OR a.seo_meta_description LIKE %s OR a.seo_focus_keyword LIKE %s OR a.seo_slug LIKE %s OR u.display_name LIKE %s OR u.user_login LIKE %s";}
	public function authors():array{global $wpdb;$sql="SELECT DISTINCT u.ID,u.display_name,u.user_login FROM {$wpdb->users} u INNER JOIN {$wpdb->posts} p ON p.post_author=u.ID WHERE p.post_type='post' AND p.post_status IN ('draft','publish','future','pending') AND EXISTS (SELECT 1 FROM {$wpdb->postmeta} pm WHERE pm.post_id=p.ID AND pm.meta_key='_aics_generated_post' AND pm.meta_value='1') ORDER BY u.display_name ASC,u.user_login ASC LIMIT 200";return $wpdb->get_results($sql,ARRAY_A)?:array();}
	private function date($value){$value=is_scalar($value)?trim((string)$value):'';if(''===$value){return '';}$date=DateTimeImmutable::createFromFormat('!Y-m-d',$value,wp_timezone());$errors=DateTimeImmutable::getLastErrors();return $date&&(false===$errors||(0===$errors['warning_count']&&0===$errors['error_count']))&&$date->format('Y-m-d')===$value?$value:false;}
}
