<?php
/** Shared retry-safe generated featured-image pipeline. @package AIContentStudio */
if ( ! defined( 'ABSPATH' ) ) { exit; }

final class AICS_Featured_Image_Pipeline_Service {
	private const MAX_ATTEMPTS=3;
	private AICS_Article_Repository $articles;private AICS_Featured_Image_Prompt_Builder $prompts;private AICS_Featured_Image_Generation_Service $generation;private AICS_Media_Library_Image_Service $media;private AICS_Featured_Image_Ownership_Service $ownership;private AICS_Featured_Image_Assignment_Service $assignment;
	public function __construct(?AICS_Article_Repository $articles=null,?AICS_Featured_Image_Prompt_Builder $prompts=null,?AICS_Featured_Image_Generation_Service $generation=null,?AICS_Media_Library_Image_Service $media=null,?AICS_Featured_Image_Ownership_Service $ownership=null,?AICS_Featured_Image_Assignment_Service $assignment=null){$this->articles=$articles??new AICS_Article_Repository();$this->prompts=$prompts??new AICS_Featured_Image_Prompt_Builder();$this->generation=$generation??new AICS_Featured_Image_Generation_Service();$this->media=$media??new AICS_Media_Library_Image_Service();$this->ownership=$ownership??new AICS_Featured_Image_Ownership_Service();$this->assignment=$assignment??new AICS_Featured_Image_Assignment_Service($this->articles,$this->ownership);}

	public function run($article_id,$actor_id=0,bool $require_enabled=true,?array $immutable_settings=null):array{
		$id=absint($article_id);$actor=absint($actor_id);$article=$this->articles->get_by_id($id);if(!$article){return $this->result(false,'article_not_found',$id,0,0,0,'',false,false);}
		$post=$this->ownership->validate_post($article);if(empty($post['success'])){return $this->result(false,$post['code'],$id,$article['wordpress_post_id'],0,0,'',false,false);}
		$existing=$this->ownership->find_for_article($article);
		if(!empty($existing['success'])){return $this->reuse($article,absint($existing['attachment_id']),$actor);}
		if('featured_image_attachment_not_found'!==$existing['code']){return $this->result(false,$existing['code'],$id,$article['wordpress_post_id'],0,0,'',false,false);}
		if('attached'===$article['featured_image_status']||'uploaded'===$article['featured_image_status']){return $this->result(false,'featured_image_attachment_missing',$id,$article['wordpress_post_id'],0,0,'',false,false);}
		if('not_requested'===$article['featured_image_status']){$initialized=$this->articles->initialize_featured_image($id,array('required'=>true,'prompt'=>$article['featured_image_prompt']??null,'alt_text'=>$this->alt($article)));if(empty($initialized['success'])){return $this->result(false,$initialized['code'],$id,$article['wordpress_post_id'],0,0,'',false,false);}$article=$this->articles->get_by_id($id);}
		if(in_array($article['featured_image_status'],array('failed','needs_attention'),true)){$reset=$this->articles->atomic_transition_featured_image_status($id,$article['featured_image_status'],'pending',array('featured_image_last_error_code'=>''));if(empty($reset['success'])){return $this->result(false,$reset['code'],$id,$article['wordpress_post_id'],0,0,'',false,false);}$article=$this->articles->get_by_id($id);}
		if(!in_array($article['featured_image_status'],array('pending','retrying'),true)){return $this->result(false,'featured_image_state_changed',$id,$article['wordpress_post_id'],0,0,'',false,false);}
		if($article['featured_image_attempts']>=self::MAX_ATTEMPTS){$this->articles->record_featured_image_error($id,$article['featured_image_status'],'needs_attention','image_retry_exhausted');return $this->result(false,'image_retry_exhausted',$id,$article['wordpress_post_id'],0,0,'',false,false);}
		$settings=null===$immutable_settings?AICS_Featured_Image_Settings::get_effective():$immutable_settings;if($require_enabled&&empty($settings['enabled'])){return $this->result(false,'image_generation_disabled',$id,$article['wordpress_post_id'],0,0,'',false,false);}
		$context=array('article_id'=>$id,'title'=>$article['title'],'excerpt'=>$article['excerpt'],'content'=>$article['content'],'seo_focus_keyword'=>$article['seo_focus_keyword'],'aspect_ratio'=>$settings['aspect_ratio'],'visual_style'=>$settings['visual_style'],'_immutable_settings'=>$immutable_settings);$prompt=AICS_Featured_Image_Prompt_Builder::sanitize_final_prompt($article['featured_image_prompt']??'');if(is_wp_error($prompt)){$prompt=$this->prompts->build($context);if(is_wp_error($prompt)){return $this->result(false,$prompt->get_error_code(),$id,$article['wordpress_post_id'],0,0,'',false,false);}$prompt_saved=$this->articles->update_featured_image_prompt($id,$prompt,$actor);if(empty($prompt_saved['success'])){return $this->result(false,$prompt_saved['code'],$id,$article['wordpress_post_id'],0,0,'',false,false);}}$context['final_prompt']=$prompt;$alt=$this->alt($article);
		$begun=$this->articles->atomic_transition_featured_image_status($id,$article['featured_image_status'],'generating',array('featured_image_attempts'=>$article['featured_image_attempts']+1,'featured_image_prompt'=>$prompt,'featured_image_alt_text'=>$alt,'featured_image_provider'=>$settings['provider'],'featured_image_model'=>$settings['model'],'featured_image_last_error_code'=>''));if(empty($begun['success'])){return $this->result(false,$begun['code'],$id,$article['wordpress_post_id'],0,0,'',false,false);}
		$started=microtime(true);$generated=null;$temporary=null;
		try{$generated=$this->generation->generate($context,$require_enabled);$temporary=$generated->get_temporary_file();AICS_Usage_Logger::log(array('user_id'=>$actor,'event_type'=>'ai_request','operation'=>'featured_image_generation','status'=>$generated->is_success()?'success':'failed','provider'=>$generated->get_provider(),'model'=>$generated->get_model(),'error_code'=>$generated->get_error_code(),'object_id'=>$id,'duration_ms'=>AICS_Usage_Logger::duration_ms($started),'metadata'=>array('source'=>'featured_image_pipeline','run_id'=>absint($article['run_id']??0),'http_status'=>$generated->get_http_status())));
			if(!$generated->is_success()){$this->generation_failure($id,$generated,$article['featured_image_attempts']+1);return $this->result(false,$generated->get_error_code(),$id,$article['wordpress_post_id'],0,0,'',false,true);}
			$uploaded=$this->media->upload($temporary,$article,array('prompt'=>$prompt,'provider'=>$generated->get_provider(),'model'=>$generated->get_model()),$alt);if(is_wp_error($uploaded)){$code=$this->controlled($uploaded->get_error_code());$target='media_library_upload_failed'===$code&&($article['featured_image_attempts']+1)<self::MAX_ATTEMPTS?'retrying':'needs_attention';$this->articles->record_featured_image_error($id,'generating',$target,$code);return $this->result(false,$code,$id,$article['wordpress_post_id'],0,0,'',false,true);}
			$attachment=absint($uploaded['attachment_id']);$saved=$this->articles->mark_featured_image_uploaded($id,'generating',$attachment,array('alt_text'=>$uploaded['alt_text'],'provider'=>$generated->get_provider(),'model'=>$generated->get_model()));if(empty($saved['success'])){if(absint(get_post_thumbnail_id($article['wordpress_post_id']))!==$attachment){wp_delete_attachment($attachment,true);}$this->articles->record_featured_image_error($id,'generating','needs_attention','attachment_persistence_failed');return $this->result(false,'attachment_persistence_failed',$id,$article['wordpress_post_id'],0,0,'',false,true);}
			$fresh=$this->articles->get_by_id($id);$assigned=$this->assignment->assign($fresh,$attachment,$actor);if(empty($assigned['success'])){$this->articles->record_featured_image_error($id,'uploaded','retrying',$this->controlled($assigned['code']));return $this->result(false,$assigned['code'],$id,$article['wordpress_post_id'],$attachment,$uploaded['width'],$uploaded['output_format'],false,true,$uploaded['height']);}
			return $this->result(true,'featured_image_pipeline_succeeded',$id,$article['wordpress_post_id'],$attachment,$uploaded['width'],$uploaded['output_format'],false,true,$uploaded['height']);
		}finally{if($temporary instanceof AICS_Temporary_Image_File){$temporary->cleanup();}}
	}

	private function reuse(array $article,int $attachment,int $actor):array{$status=$article['featured_image_status'];$details=$this->attachment_details($attachment);if('attached'===$status){$thumb=absint(get_post_thumbnail_id($article['wordpress_post_id']));return $thumb===$attachment?$this->result(true,'featured_image_already_attached',$article['id'],$article['wordpress_post_id'],$attachment,$details['width'],$details['format'],true,false,$details['height']):$this->result(false,'featured_image_ownership_conflict',$article['id'],$article['wordpress_post_id'],$attachment,$details['width'],$details['format'],true,false,$details['height']);}
		if('uploaded'!==$status){$saved=$this->articles->mark_featured_image_uploaded($article['id'],$status,$attachment,array('alt_text'=>$this->alt($article),'provider'=>(string)get_post_meta($attachment,'_aics_provider',true),'model'=>(string)get_post_meta($attachment,'_aics_model',true)));if(empty($saved['success'])){return $this->result(false,'attachment_persistence_failed',$article['id'],$article['wordpress_post_id'],$attachment,0,'',true,false);}$article=$this->articles->get_by_id($article['id']);}
		$assigned=$this->assignment->assign($article,$attachment,$actor);return empty($assigned['success'])?$this->result(false,$assigned['code'],$article['id'],$article['wordpress_post_id'],$attachment,$details['width'],$details['format'],true,false,$details['height']):$this->result(true,'featured_image_pipeline_succeeded',$article['id'],$article['wordpress_post_id'],$attachment,$details['width'],$details['format'],true,false,$details['height']);}
	private function attachment_details(int $attachment):array{$meta=wp_get_attachment_metadata($attachment);$mime=get_post_mime_type($attachment);$formats=array('image/png'=>'png','image/jpeg'=>'jpeg','image/webp'=>'webp');return array('width'=>absint(is_array($meta)?($meta['width']??0):0),'height'=>absint(is_array($meta)?($meta['height']??0):0),'format'=>$formats[$mime]??'');}
	private function generation_failure(int $id,AICS_Image_Generation_Result $result,int $attempts):void{$code=$this->controlled($result->get_error_code());$target=$result->is_retryable()&&$attempts<self::MAX_ATTEMPTS?'retrying':($attempts>=self::MAX_ATTEMPTS?'needs_attention':'failed');$this->articles->record_featured_image_error($id,'generating',$target,$attempts>=self::MAX_ATTEMPTS?'image_retry_exhausted':$code);}
	private function controlled(string $code):string{return AICS_Featured_Image_State::is_error_supported($code)?$code:'image_provider_request_failed';}
	private function alt(array $article):string{$title=trim(sanitize_text_field((string)($article['title']??'')));$value=sprintf(__('Featured image for %s','ai-content-studio'),$title);return function_exists('mb_substr')?mb_substr($value,0,250,'UTF-8'):substr($value,0,250);}
	private function result(bool $success,string $code,int $article,int $post,int $attachment,int $width,string $format,bool $reused,bool $generated,int $height=0):array{return array('success'=>$success,'code'=>sanitize_key($code),'message'=>$success?__('Featured-image pipeline succeeded.','ai-content-studio'):AICS_Featured_Image_State::error_label($code),'article_id'=>$article,'post_id'=>$post,'attachment_id'=>$attachment,'width'=>$width,'height'=>$height,'format'=>sanitize_key($format),'reused'=>$reused,'generated'=>$generated);}
}
