<?php
/** Native WordPress delivery for persistent automation articles. @package AIContentStudio */
if(!defined('ABSPATH')){exit;}

final class AICS_Automation_Delivery_Service{
	private AICS_Article_Repository $articles;
	public function __construct(?AICS_Article_Repository $articles=null){$this->articles=$articles??new AICS_Article_Repository();}

	public function schedule_article_post($article_id,$scheduled_for_utc):array{$article=$this->articles->get_by_id(absint($article_id));if(!$article){return $this->result(false,'article_not_found',absint($article_id),0,null,false,false);}$owned=$this->validate_article_post_ownership($article);if(empty($owned['success'])){return $this->result(false,$owned['code'],$article['id'],0,null,false,false);}$post=$owned['post'];if('publish'===$post->post_status){$at=$this->post_utc($post)??current_time('mysql',true);$sync=$this->articles->mark_published($article['id'],$post->ID,$at,0);return $this->result(!empty($sync['success']),empty($sync['success'])?'article_publish_sync_failed':'wordpress_post_already_published',$article['id'],$post->ID,null,false,empty($sync['success']));}if('future'===$post->post_status){$slot=$this->post_utc($post);if(!$slot){return $this->result(false,'wordpress_schedule_failed',$article['id'],$post->ID,null,false,false);}$sync=$this->articles->mark_scheduled($article['id'],$post->ID,$slot,0);return $this->result(!empty($sync['success']),empty($sync['success'])?'article_schedule_sync_failed':'wordpress_post_already_scheduled',$article['id'],$post->ID,$slot,false,empty($sync['success']));}if('draft'!==$post->post_status){return $this->result(false,'invalid_wordpress_post_status',$article['id'],$post->ID,null,false,false);}$slot=$this->datetime($scheduled_for_utc);if(!$slot||$slot<=current_time('mysql',true)){return $this->result(false,'no_future_publishing_slot',$article['id'],$post->ID,null,false,false);}$saved=$this->articles->update_planned_publish_at($article['id'],$slot,0);if(empty($saved['success'])){return $this->result(false,'planned_publish_time_save_failed',$article['id'],$post->ID,$slot,false,true);}$updated=wp_update_post(array('ID'=>$post->ID,'post_status'=>'future','post_date'=>get_date_from_gmt($slot,'Y-m-d H:i:s'),'post_date_gmt'=>$slot),true);if(is_wp_error($updated)||absint($updated)!==$post->ID){return $this->result(false,'wordpress_schedule_failed',$article['id'],$post->ID,$slot,false,true);}$post=get_post($post->ID);if(!$post){return $this->result(false,'article_post_missing',$article['id'],0,$slot,false,false);}if('publish'===$post->post_status){$sync=$this->articles->mark_published($article['id'],$post->ID,$this->post_utc($post)??current_time('mysql',true),0);return $this->result(!empty($sync['success']),empty($sync['success'])?'article_publish_sync_failed':'wordpress_post_published',$article['id'],$post->ID,null,true,empty($sync['success']));}if('future'!==$post->post_status||$slot!==$this->post_utc($post)){return $this->result(false,'wordpress_schedule_failed',$article['id'],$post->ID,$slot,false,true);}$sync=$this->articles->mark_scheduled($article['id'],$post->ID,$slot,0);return $this->result(!empty($sync['success']),empty($sync['success'])?'article_schedule_sync_failed':'wordpress_post_scheduled',$article['id'],$post->ID,$slot,true,empty($sync['success']));}

	public function publish_article_post($article_id):array{$article=$this->articles->get_by_id(absint($article_id));if(!$article){return $this->result(false,'article_not_found',absint($article_id),0,null,false,false);}$owned=$this->validate_article_post_ownership($article);if(empty($owned['success'])){return $this->result(false,$owned['code'],$article['id'],0,null,false,false);}$post=$owned['post'];if('publish'===$post->post_status){$sync=$this->articles->mark_published($article['id'],$post->ID,$this->post_utc($post)??current_time('mysql',true),0);return $this->result(!empty($sync['success']),empty($sync['success'])?'article_publish_sync_failed':'wordpress_post_already_published',$article['id'],$post->ID,null,false,empty($sync['success']));}if('draft'!==$post->post_status){return $this->result(false,'invalid_wordpress_post_status',$article['id'],$post->ID,null,false,false);}$utc=current_time('mysql',true);$local=current_time('mysql',false);$updated=wp_update_post(array('ID'=>$post->ID,'post_status'=>'publish','post_date'=>$local,'post_date_gmt'=>$utc),true);if(is_wp_error($updated)||absint($updated)!==$post->ID){return $this->result(false,'wordpress_publish_failed',$article['id'],$post->ID,null,false,true);}$post=get_post($post->ID);if(!$post||'publish'!==$post->post_status){return $this->result(false,'wordpress_publish_failed',$article['id'],absint($updated),null,false,true);}$sync=$this->articles->mark_published($article['id'],$post->ID,$this->post_utc($post)??$utc,0);return $this->result(!empty($sync['success']),empty($sync['success'])?'article_publish_sync_failed':'wordpress_post_published',$article['id'],$post->ID,null,true,empty($sync['success']));}

	public function validate_article_post_ownership(array $article):array{$post_id=absint($article['wordpress_post_id']??0);if(!$post_id){return array('success'=>false,'code'=>'article_post_missing','post'=>null);}$post=get_post($post_id);if(!$post||'post'!==$post->post_type){return array('success'=>false,'code'=>'article_post_missing','post'=>null);}$valid=1===absint(get_post_meta($post_id,'_aics_generated_post',true))&&'automation'===sanitize_key((string)get_post_meta($post_id,'_aics_source',true))&&absint($article['id'])===absint(get_post_meta($post_id,'_aics_article_id',true))&&absint($article['run_id'])===absint(get_post_meta($post_id,'_aics_run_id',true))&&absint($article['profile_id'])===absint(get_post_meta($post_id,'_aics_profile_id',true));$uuid=sanitize_text_field((string)get_post_meta($post_id,'_aics_article_uuid',true));if($uuid&&$uuid!==$article['article_uuid']){$valid=false;}return array('success'=>$valid,'code'=>$valid?'wordpress_post_owned':'wordpress_post_ownership_conflict','post'=>$valid?$post:null);}
	private function post_utc(WP_Post $post):?string{return $this->datetime($post->post_date_gmt);}
	private function datetime($value):?string{if(!is_scalar($value)){return null;}$value=(string)$value;$d=DateTimeImmutable::createFromFormat('!Y-m-d H:i:s',$value,new DateTimeZone('UTC'));$e=DateTimeImmutable::getLastErrors();return false!==$d&&(false===$e||(0===$e['warning_count']&&0===$e['error_count']))&&$d->format('Y-m-d H:i:s')===$value?$value:null;}
	private function result(bool $success,string $code,int $article,int $post,?string $slot,bool $changed,bool $retryable):array{return array('success'=>$success,'code'=>$code,'article_id'=>$article,'post_id'=>$post,'scheduled_for'=>$slot,'changed'=>$changed,'retryable'=>$retryable);}
}
