<?php
if(!defined('ABSPATH')){exit;}
final class AICS_Manual_SEO_Application_Service{
	public function __construct(private ?AICS_Article_Repository $articles=null,private ?AICS_SEO_Workflow_Service $workflow=null){$this->articles=$articles??new AICS_Article_Repository();$this->workflow=$workflow??new AICS_SEO_Workflow_Service($this->articles);}
	public function preview(int $id,int $user):array{$a=$this->load($id,$user);if(is_wp_error($a)){return array('success'=>false,'code'=>$a->get_error_code());}$s=$this->settings($user);$resolved=(new AICS_SEO_Plugin_Detector())->resolve($s['target_plugin']);return array('success'=>true,'article'=>$a,'settings'=>$s,'adapter'=>$resolved,'internal_links'=>(new AICS_Internal_Link_Recommendation_Service())->recommend($a,(new AICS_Internal_Link_Candidate_Service())->discover($a),$s['links']['internal_enabled']?$s['links']['internal_maximum']:0),'trusted_external_urls'=>$s['trusted_external_urls'],'image_placement'=>$s['content_image']['placement']);}
	public function apply(int $id,int $user):array{$a=$this->load($id,$user);if(is_wp_error($a)){return array('success'=>false,'code'=>$a->get_error_code());}$r=$this->workflow->apply($id,$this->settings($user),$user);if(empty($r['success'])&&empty($r['persisted'])){$this->articles->persist_seo_application_error($id,$r['reason_code']??$r['code']??'seo_adapter_application_failed',$user);}return $r;}
	private function load(int $id,int $user){$a=$this->articles->get_by_id($id);return !$a?new WP_Error('seo_post_not_found'):('manual'!==$a['source_type']||$a['created_by']!==$user?new WP_Error('seo_post_ownership_invalid'):$a);}
	private function settings(int $u):array{$state=get_transient('aics_content_inputs_'.$u);return AICS_SEO_Configuration::normalize_stored(is_array($state)?($state['seo_settings']??array()):array(),true);}
}
