<?php
if(!defined('ABSPATH')){exit;}
final class AICS_Native_WordPress_SEO_Adapter implements AICS_SEO_Adapter_Interface{
	public function get_key():string{return 'native';}public function get_label():string{return __('Native WordPress','ai-content-studio');}public function is_available():bool{return true;}public function get_version():string{return get_bloginfo('version');}public function get_compatibility_status():string{return 'compatible';}public function validate_data(AICS_SEO_Data $d){$v=$d->to_adapter_data();return ''!==$v['slug']&&''!==$v['excerpt']?true:new WP_Error('seo_data_incomplete');}
	public function apply_to_post(int $id,AICS_SEO_Data $d){if(!$this->owned($id)){return new WP_Error('seo_post_ownership_invalid');}$v=$d->to_adapter_data();$r=wp_update_post(array('ID'=>$id,'post_name'=>$v['slug'],'post_excerpt'=>$v['excerpt']),true);if(is_wp_error($r)){return new WP_Error('seo_native_application_failed');}$verified=$this->verify_application($id,$d);if(is_wp_error($verified)){return $verified;}return AICS_SEO_Application_Result::success(array('adapter_key'=>'native','adapter_label'=>$this->get_label(),'post_id'=>$id,'applied_fields'=>array('slug','excerpt'),'verified_fields'=>$verified,'native_applied'=>true,'verification_passed'=>true,'applied_at'=>current_time('mysql',true)));}
	public function read_from_post(int $id){$p=get_post($id);return !$p?new WP_Error('seo_post_not_found'):array('slug'=>(string)$p->post_name,'excerpt'=>(string)$p->post_excerpt);}
	public function verify_application(int $id,AICS_SEO_Data $d){$r=$this->read_from_post($id);if(is_wp_error($r)){return $r;}$v=$d->to_adapter_data();return $r['slug']===$v['slug']&&$r['excerpt']===$v['excerpt']?array('slug','excerpt'):new WP_Error('seo_adapter_verification_failed');}
	public function refresh_post_seo_data(int $id){clean_post_cache($id);return true;}public function supports_focus_keyword():bool{return false;}public function supports_seo_title():bool{return false;}public function supports_meta_description():bool{return false;}public function supports_score_reading():bool{return false;}private function owned(int $id):bool{return get_post($id)&&1===absint(get_post_meta($id,'_aics_generated_post',true))&&absint(get_post_meta($id,'_aics_article_id',true))>0;}
}
