<?php
if(!defined('ABSPATH')){exit;}
final class AICS_SEO_Workflow_Service{
	public function __construct(private ?AICS_Article_Repository $articles=null,private ?AICS_SEO_Generation_Service $generator=null){$this->articles=$articles??new AICS_Article_Repository();$this->generator=$generator??new AICS_SEO_Generation_Service();}
	public function generate(int $article_id,array $settings,array $context=array(),int $user=0):array{$a=$this->articles->get_by_id($article_id);if(!$a){return $this->fail('seo_post_not_found',false);}if(!$settings['enabled']){return array('success'=>true,'code'=>'seo_disabled','complete'=>true,'provider_called'=>false);}if(in_array($a['seo_status'],array('generated','review_required','approved','applied'),true)&&''!==trim((string)$a['seo_title'])){return array('success'=>true,'code'=>'seo_already_generated','complete'=>true,'provider_called'=>false);}if(!AICS_Settings::has_openai_api_key()){return $this->fail('seo_provider_not_configured',false);}$resolved=(new AICS_SEO_Plugin_Detector())->resolve((string)$settings['target_plugin']);if(empty($resolved['available'])){return $this->fail('seo_target_plugin_unavailable',false);}$this->articles->increment_seo_attempt($article_id,'generation');$result=$this->generator->generate($a,$settings,$context);if(!$result->is_success()){return $this->fail($result->get_code(),in_array($result->get_code(),array('seo_generation_failed','invalid_seo_generation_response'),true),true);}$analysis=$result->get_analysis();$target=$resolved['key'];if('manual'===$a['source_type']){$status=empty($analysis['blocking_issues'])?'generated':'review_required';$saved=$this->articles->persist_seo_result($article_id,$result->get_data(),$analysis,$target,$status,$user);}else{$saved=$this->articles->persist_automation_seo($article_id,$result->get_data(),$analysis,$target,$result->get_provider(),$result->get_model());}return empty($saved['success'])?$this->fail('seo_generation_failed',true,true):array('success'=>true,'code'=>'seo_generated','complete'=>true,'provider_called'=>true,'analysis'=>$analysis);}
	public function apply(int $article_id,array $settings,int $user=0):array{
		$a=$this->articles->get_by_id($article_id);if(!$a){return $this->fail('seo_post_not_found',false);}if(empty($settings['enabled'])){return array('success'=>true,'code'=>'seo_disabled','complete'=>true);}$gate_service=new AICS_SEO_Quality_Gate();
		if('applied'===$a['seo_status']&&empty($a['seo_last_error_code'])){$report=is_array($a['seo_application_report']??null)?$a['seo_application_report']:array();$current=$gate_service->evaluate($a,$settings,true,!empty($report['verification_passed']));if($current['passed']){return $this->success('seo_already_applied',$current,$report);}}
		if(!in_array($a['seo_status'],array('generated','review_required','approved','needs_attention','applied'),true)){return $this->fail('seo_data_incomplete',false);}$pre_settings=$settings;$pre_settings['quality_gate']['require_successful_application']=false;$pre_settings['quality_gate']['require_adapter_verification']=false;$pre=$gate_service->evaluate($a,$pre_settings,true,true);if(!$pre['passed']){return $this->gate_failure($pre,false);}
		$resolved=(new AICS_SEO_Plugin_Detector())->resolve((string)$settings['target_plugin']);if(empty($resolved['available'])){return $this->fail('seo_target_plugin_unavailable',false);}$this->articles->increment_seo_attempt($article_id,'application');$native=(new AICS_Native_SEO_Application_Service($this->articles))->apply($a,$settings,$user);if(empty($native['success'])){return $this->fail($native['code']??'seo_native_application_failed',!empty($native['retryable']));}$adapter=AICS_SEO_Adapter_Factory::get($resolved['key']);if(is_wp_error($adapter)){return $this->fail($adapter->get_error_code(),false);}$plugin=null;if('native'!==$adapter->get_key()){$plugin=$adapter->apply_to_post(absint($a['wordpress_post_id']),$native['data']);if(is_wp_error($plugin)){return $this->fail($plugin->get_error_code(),in_array($plugin->get_error_code(),array('seo_adapter_application_failed','seo_plugin_refresh_failed'),true));}}
		$report=$plugin instanceof AICS_SEO_Application_Result?$plugin->to_array():array('adapter_key'=>'native','adapter_label'=>__('Native WordPress','ai-content-studio'),'post_id'=>absint($a['wordpress_post_id']),'applied_fields'=>array('slug','excerpt','content','categories','tags','image_alt_text'),'verified_fields'=>array('slug','excerpt'),'warnings'=>array(),'native_applied'=>true,'plugin_applied'=>false,'verification_passed'=>true,'refresh_requested'=>false,'applied_at'=>current_time('mysql',true));$report['native_applied']=true;$candidate=$a;$candidate['content']=$native['content'];$candidate['seo_analysis']=$native['analysis'];$candidate['seo_analyzed_at']=current_time('mysql',true);$final_gate=$gate_service->evaluate($candidate,$settings,true,!empty($report['verification_passed']));$report['quality_gate']=$this->safe_gate($final_gate);$status=$final_gate['passed']?'applied':'needs_attention';$error=$final_gate['passed']?'':'seo_quality_gate_failed';$saved=$this->articles->persist_seo_application_outcome($article_id,$report,$native['analysis'],$adapter->get_key(),$adapter->get_version(),$native['content'],$native['internal_links'],$native['external_links'],$native['alt'],$status,$error,$user);if(empty($saved['success'])){return $this->fail('seo_adapter_application_failed',true);}if(!$final_gate['passed']){return $this->gate_failure($final_gate,true,$report);}return array_merge($this->success('seo_application_succeeded',$final_gate,$report),array('analysis'=>$native['analysis'],'image'=>$native['image']));
	}
	private function safe_gate(array $g):array{return array('passed'=>!empty($g['passed']),'score'=>absint($g['score']??0),'minimum'=>absint($g['minimum']??0),'failed_conditions'=>array_slice(array_values(array_filter(array_map('sanitize_key',$g['failed_conditions']??array()))),0,10),'blocking_analysis_ids'=>array_slice(array_values(array_filter(array_map('sanitize_key',$g['blocking_analysis_ids']??array()))),0,10),'environment_notice_ids'=>array_slice(array_values(array_filter(array_map(static fn($v)=>sanitize_key(is_array($v)?($v['id']??''):$v),$g['environment_notices']??array()))),0,10));}
	private function success(string $code,array $gate,array $report):array{return array('success'=>true,'code'=>$code,'message'=>__('SEO application and verification passed the configured Quality Gate.','ai-content-studio'),'complete'=>true,'retryable'=>false,'quality_gate'=>$gate,'application'=>$report,'persisted'=>true);}
	private function gate_failure(array $gate,bool $persisted,array $report=array()):array{$reason=(string)($gate['failed_conditions'][0]??'seo_quality_gate_failed');$message='seo_readiness_below_minimum'===$reason?sprintf(__('SEO Readiness is %1$d. This workflow requires at least %2$d.','ai-content-studio'),absint($gate['score']??0),absint($gate['minimum']??0)):('seo_adapter_verification_failed'===$reason?__('The selected SEO adapter metadata could not be verified after saving.','ai-content-studio'):__('SEO application requires attention because a blocking Quality Gate condition remains.','ai-content-studio'));return array('success'=>false,'code'=>'seo_quality_gate_failed','reason_code'=>$reason,'message'=>$message,'complete'=>true,'retryable'=>false,'quality_gate'=>$gate,'application'=>$report,'persisted'=>$persisted);}
	private function fail(string $code,bool $retryable,bool $provider=false):array{return array('success'=>false,'code'=>substr(sanitize_key($code),0,100),'retryable'=>$retryable,'provider_called'=>$provider,'complete'=>false,'persisted'=>false);}
}
