<?php
/** Global featured-image configuration stored within the existing settings option. @package AIContentStudio */
if ( ! defined( 'ABSPATH' ) ) { exit; }

final class AICS_Featured_Image_Settings {
	private const OPTION_NAME='aics_settings'; private const OPTION_KEY='featured_images';
	private const DEFAULTS=array('enabled'=>false,'provider'=>'openai','model'=>AICS_OpenAI_Image_Provider::DEFAULT_MODEL,'aspect_ratio'=>'landscape','quality'=>'standard','output_format'=>'png','visual_style'=>'editorial');
	public static function get_effective():array{$stored=get_option(self::OPTION_NAME,array());$image=is_array($stored)&&isset($stored[self::OPTION_KEY])&&is_array($stored[self::OPTION_KEY])?$stored[self::OPTION_KEY]:array();$provider=is_scalar($image['provider']??null)?sanitize_key((string)$image['provider']):self::DEFAULTS['provider'];$adapter=AICS_Image_Provider_Factory::create($provider);if(is_wp_error($adapter)){$provider=self::DEFAULTS['provider'];$adapter=AICS_Image_Provider_Factory::create($provider);}$capabilities=$adapter->get_capabilities();return array('enabled'=>self::boolean($image['enabled']??false),'provider'=>$provider,'model'=>self::fallback($image['model']??'',$capabilities['supported_models'],$capabilities['default_model']),'aspect_ratio'=>self::fallback($image['aspect_ratio']??'',$capabilities['supported_aspect_ratios'],self::DEFAULTS['aspect_ratio']),'quality'=>self::fallback($image['quality']??'',$capabilities['supported_quality_levels'],self::DEFAULTS['quality']),'output_format'=>self::fallback($image['output_format']??'',$capabilities['supported_output_formats'],self::DEFAULTS['output_format']),'visual_style'=>AICS_Featured_Image_Prompt_Builder::normalize_style($image['visual_style']??self::DEFAULTS['visual_style']));}
	/** @return array|WP_Error */
	public static function validate(array $input){$provider=is_scalar($input['provider']??null)?sanitize_key((string)$input['provider']):'';$adapter=AICS_Image_Provider_Factory::create($provider);if(is_wp_error($adapter)){return new WP_Error('invalid-image-provider',__('The selected image provider is invalid. No image settings were changed.','ai-content-studio'));}$cap=$adapter->get_capabilities();$model=self::identifier($input['model']??'',100);if(!in_array($model,$cap['supported_models'],true)){return new WP_Error('invalid-image-model',__('The selected image model is invalid. No image settings were changed.','ai-content-studio'));}$checks=array('aspect_ratio'=>array('invalid-image-aspect-ratio','supported_aspect_ratios'),'quality'=>array('invalid-image-quality','supported_quality_levels'),'output_format'=>array('invalid-image-output-format','supported_output_formats'));$out=array('enabled'=>self::boolean($input['enabled']??false),'provider'=>$provider,'model'=>$model);foreach($checks as $key=>$definition){$value=is_scalar($input[$key]??null)?sanitize_key((string)$input[$key]):'';if(!in_array($value,$cap[$definition[1]],true)){return new WP_Error($definition[0],__('One or more image settings are invalid. No image settings were changed.','ai-content-studio'));}$out[$key]=$value;}$style=AICS_Featured_Image_Prompt_Builder::normalize_style($input['visual_style']??self::DEFAULTS['visual_style']);if(array_key_exists('visual_style',$input)&&$style!==sanitize_key((string)$input['visual_style'])){return new WP_Error('invalid-image-visual-style',__('The selected visual style is invalid. No image settings were changed.','ai-content-studio'));}$out['visual_style']=$style;return $out;}
	/** @return true|WP_Error */
	public static function update(array $input){$validated=self::validate($input);if(is_wp_error($validated)){return $validated;}$settings=get_option(self::OPTION_NAME,array());if(!is_array($settings)){$settings=array();}$settings[self::OPTION_KEY]=$validated;if(false===get_option(self::OPTION_NAME,false)){add_option(self::OPTION_NAME,$settings,'',false);}else{update_option(self::OPTION_NAME,$settings,false);}return true;}
	public static function configuration_status():array{$stored=get_option(self::OPTION_NAME,array());if(is_array($stored)&&isset($stored[self::OPTION_KEY])){$validation=self::validate(is_array($stored[self::OPTION_KEY])?$stored[self::OPTION_KEY]:array());if(is_wp_error($validation)){return array('success'=>false,'code'=>'image_settings_invalid','message'=>__('Saved image settings are no longer supported. Review and save the displayed safe defaults.','ai-content-studio'));}}$settings=self::get_effective();if(!$settings['enabled']){return array('success'=>false,'code'=>'image_generation_disabled','message'=>__('Image generation is disabled.','ai-content-studio'));}$provider=AICS_Image_Provider_Factory::create($settings['provider']);return is_wp_error($provider)?array('success'=>false,'code'=>'image_provider_invalid','message'=>__('The image provider is not configured.','ai-content-studio')):$provider->validate_configuration();}
	private static function boolean($value):bool{return true===filter_var($value,FILTER_VALIDATE_BOOLEAN);}
	private static function fallback($value,array $allowed,string $default):string{$value=is_scalar($value)?sanitize_text_field((string)$value):'';return in_array($value,$allowed,true)?$value:$default;}
	private static function identifier($value,int $max):string{$value=is_scalar($value)?trim(sanitize_text_field((string)$value)):'';$length=function_exists('mb_strlen')?mb_strlen($value,'UTF-8'):strlen($value);return $length<=$max&&1===preg_match('/^[a-zA-Z0-9._:-]+$/',$value)?$value:'';}
	private function __construct(){}
}
