<?php
if(!defined('ABSPATH')){exit;}
final class AICS_AIOSEO_Adapter implements AICS_SEO_Adapter_Interface{
	private const MODEL='AIOSEO\\Plugin\\Common\\Models\\Post';
	public function get_key():string{return 'aioseo';}public function get_label():string{return 'All in One SEO';}public function is_available():bool{return function_exists('aioseo')&&class_exists(self::MODEL);}public function get_version():string{return defined('AIOSEO_VERSION')?(string)AIOSEO_VERSION:'';}public function get_compatibility_status():string{return $this->is_available()?'compatible':'unavailable';}
	public function validate_data(AICS_SEO_Data $data){$v=$data->to_adapter_data();return ''!==$v['seo_title']&&''!==$v['meta_description']?true:new WP_Error('seo_data_incomplete');}
	public function apply_to_post(int $post_id,AICS_SEO_Data $data){if(!$this->is_available()){return new WP_Error('seo_target_plugin_unavailable');}if(!$this->owned($post_id)){return new WP_Error('seo_post_ownership_invalid');}$v=$data->to_adapter_data();try{$class=self::MODEL;$model=$class::getPost($post_id);$model->title=$v['seo_title'];$model->description=$v['meta_description'];$model->keyphrases=array('focus'=>array('keyphrase'=>$v['focus_keyword'],'score'=>0,'analysis'=>array()),'additional'=>array());$model->save();}catch(Throwable $e){return new WP_Error('seo_adapter_application_failed');}$verified=$this->verify_application($post_id,$data);if(is_wp_error($verified)){return $verified;}return AICS_SEO_Application_Result::success(array('adapter_key'=>$this->get_key(),'adapter_label'=>$this->get_label(),'post_id'=>$post_id,'applied_fields'=>array('seo_title','meta_description','focus_keyword'),'verified_fields'=>$verified,'plugin_applied'=>true,'verification_passed'=>true,'refresh_requested'=>true,'applied_at'=>current_time('mysql',true)));}
	public function read_from_post(int $post_id){if(!$this->is_available()){return new WP_Error('seo_target_plugin_unavailable');}try{$class=self::MODEL;$m=$class::getPost($post_id);$kp=is_object($m->keyphrases??null)?$m->keyphrases:(object)(is_array($m->keyphrases??null)?$m->keyphrases:array());$focus='';if(isset($kp->focus->keyphrase)){$focus=(string)$kp->focus->keyphrase;}elseif(isset($kp->focus['keyphrase'])){$focus=(string)$kp->focus['keyphrase'];}return array('seo_title'=>sanitize_text_field((string)($m->title??'')),'meta_description'=>sanitize_text_field((string)($m->description??'')),'focus_keyword'=>sanitize_text_field($focus));}catch(Throwable $e){return new WP_Error('seo_adapter_application_failed');}}
	public function verify_application(int $post_id,AICS_SEO_Data $data){$r=$this->read_from_post($post_id);if(is_wp_error($r)){return $r;}$v=$data->to_adapter_data();$ok=array();foreach(array('seo_title','meta_description','focus_keyword') as $f){if(trim($r[$f]??'')!==trim($v[$f]??'')){return new WP_Error('seo_adapter_verification_failed');}$ok[]=$f;}return $ok;}
	public function refresh_post_seo_data(int $post_id){clean_post_cache($post_id);do_action('aioseo_post_updated',$post_id);return true;}public function supports_focus_keyword():bool{return true;}public function supports_seo_title():bool{return true;}public function supports_meta_description():bool{return true;}public function supports_score_reading():bool{return false;}private function owned(int $id):bool{return get_post($id)&&1===absint(get_post_meta($id,'_aics_generated_post',true))&&absint(get_post_meta($id,'_aics_article_id',true))>0;}
}
