<?php
/** Shared persistence and post ownership for Manual Studio articles. @package AIContentStudio */
if ( ! defined( 'ABSPATH' ) ) { exit; }

final class AICS_Manual_Article_Persistence_Service {
	private AICS_Article_Repository $articles;private AICS_Post_Generator $posts;
	public function __construct(?AICS_Article_Repository $articles=null,?AICS_Post_Generator $posts=null){$this->articles=$articles??new AICS_Article_Repository();$this->posts=$posts??new AICS_Post_Generator();}

	public function persist_generated(array $article_data,$user_id,$existing_article_id=0):array{$user=absint($user_id);$prepared=$this->posts->prepare_generated_article($article_data);if(is_wp_error($prepared)){return $this->result(false,'invalid_manual_article',0,'',0,false);}$existing=absint($existing_article_id);if($existing){$loaded=$this->load($existing,$user);if(empty($loaded['success'])){return $loaded;}$updated=$this->articles->update_manual_article($existing,$prepared,$user);return empty($updated['success'])?$this->result(false,$updated['code'],$existing,$loaded['article']['article_uuid'],0,false):$this->result(true,'manual_article_updated',$existing,$loaded['article']['article_uuid'],$loaded['article']['wordpress_post_id'],true,$this->articles->get_by_id($existing));}$created=$this->articles->create_manual_article($prepared,$user);return empty($created['success'])?$this->result(false,$created['code'],0,'',0,false):$this->result(true,'manual_article_created',$created['article_id'],$created['uuid'],0,false,$this->articles->get_by_id($created['article_id']));}

	public function load($identity,$user_id):array{$user=absint($user_id);$article=is_scalar($identity)&&ctype_digit((string)$identity)?$this->articles->get_by_id(absint($identity)):$this->articles->get_by_uuid(is_scalar($identity)?(string)$identity:'');if(!$article){return $this->result(false,'article_not_found',0,'',0,false);}if('manual'!==$article['source_type']||$user<1||$article['created_by']!==$user){return $this->result(false,'manual_article_not_owned',$article['id'],$article['article_uuid'],0,false);}return $this->result(true,'manual_article_loaded',$article['id'],$article['article_uuid'],$article['wordpress_post_id'],true,$article);}

	public function update($article_id,array $article_data,$user_id):array{$loaded=$this->load($article_id,$user_id);if(empty($loaded['success'])){return $loaded;}$prepared=$this->posts->prepare_edited_article($article_data['title']??'',$article_data['excerpt']??'',$article_data['content']??'');if(is_wp_error($prepared)){return $this->result(false,$prepared->get_error_code(),$loaded['article_id'],$loaded['uuid'],$loaded['post_id'],false);}$updated=$this->articles->update_manual_article($loaded['article_id'],$prepared,absint($user_id));return empty($updated['success'])?$this->result(false,$updated['code'],$loaded['article_id'],$loaded['uuid'],$loaded['post_id'],false):$this->result(true,'manual_article_updated',$loaded['article_id'],$loaded['uuid'],$loaded['post_id'],true,$this->articles->get_by_id($loaded['article_id']));}

	public function create_or_get_draft($article_id,$user_id,array $context=array()):array{$loaded=$this->load($article_id,$user_id);if(empty($loaded['success'])){return $loaded;}$article=$loaded['article'];$post_id=absint($article['wordpress_post_id']);if($post_id){return $this->valid_post($post_id,$article)?$this->result(true,'wordpress_draft_already_exists',$article['id'],$article['article_uuid'],$post_id,true,$article):$this->result(false,'manual_post_ownership_conflict',$article['id'],$article['article_uuid'],$post_id,false);}
		$found=get_posts(array('post_type'=>'post','post_status'=>'any','fields'=>'ids','posts_per_page'=>2,'no_found_rows'=>true,'meta_key'=>'_aics_article_id','meta_value'=>(string)$article['id']));if(count($found)>1){return $this->result(false,'manual_post_ownership_conflict',$article['id'],$article['article_uuid'],0,false);}if($found){$candidate=absint($found[0]);if(!$this->valid_post($candidate,$article)){return $this->result(false,'manual_post_ownership_conflict',$article['id'],$article['article_uuid'],$candidate,false);}$associated=$this->articles->associate_wordpress_post($article['id'],$candidate,'draft_created',absint($user_id));return empty($associated['success'])?$this->result(false,'manual_post_association_failed',$article['id'],$article['article_uuid'],0,false):$this->result(true,'wordpress_draft_already_exists',$article['id'],$article['article_uuid'],$candidate,true,$this->articles->get_by_id($article['id']));}
		$metadata=array('_aics_generated_post'=>1,'_aics_source'=>'manual','_aics_article_id'=>$article['id'],'_aics_article_uuid'=>$article['article_uuid'],'_aics_created_by_user'=>absint($user_id),'_aics_generation_timestamp'=>absint($context['generated_at']??current_time('timestamp',true)),'_aics_primary_keyword'=>sanitize_text_field((string)($context['primary_keyword']??'')),'_aics_search_intent'=>sanitize_key((string)($context['search_intent']??'')),'_aics_requested_tone'=>sanitize_key((string)($context['tone']??'')),'_aics_requested_length'=>sanitize_key((string)($context['length']??'')));
		$created=$this->posts->create_draft_from_article($article,array('author_id'=>absint($user_id)),$metadata);$post_id=absint($created['post_id']??0);if(empty($created['success'])||!$post_id){return $this->result(false,$created['code']??'wordpress-draft-creation-failed',$article['id'],$article['article_uuid'],0,false);}if(!$this->valid_post($post_id,$article)){wp_delete_post($post_id,true);return $this->result(false,'manual_post_metadata_failed',$article['id'],$article['article_uuid'],0,false);}$associated=$this->articles->associate_wordpress_post($article['id'],$post_id,'draft_created',absint($user_id));if(empty($associated['success'])){wp_delete_post($post_id,true);return $this->result(false,'manual_post_association_failed',$article['id'],$article['article_uuid'],0,false);}return $this->result(true,'wordpress_draft_created',$article['id'],$article['article_uuid'],$post_id,false,$this->articles->get_by_id($article['id']));}

	private function valid_post(int $post_id,array $article):bool{$post=get_post($post_id);return $post instanceof WP_Post&&'post'===$post->post_type&&'trash'!==$post->post_status&&'1'===(string)get_post_meta($post_id,'_aics_generated_post',true)&&'manual'===(string)get_post_meta($post_id,'_aics_source',true)&&absint(get_post_meta($post_id,'_aics_article_id',true))===$article['id']&&sanitize_text_field((string)get_post_meta($post_id,'_aics_article_uuid',true))===$article['article_uuid'];}
	private function result(bool $success,string $code,int $article,string $uuid,int $post,bool $reused,array $data=array()):array{return array('success'=>$success,'code'=>sanitize_key($code),'article_id'=>$article,'uuid'=>$uuid,'post_id'=>$post,'reused'=>$reused,'article'=>$data);}
}
