<?php
/** Human approval workflow coordination. @package AIContentStudio */
if(!defined('ABSPATH')){exit;}
final class AICS_Approval_Workflow_Service{
	private const IDEA_REJECTIONS=array('off_topic','duplicate_concept','low_business_value','not_for_target_audience','not_suitable');
	private const ARTICLE_REJECTIONS=array('needs_revision','off_brand','fact_check_required','quality_issue','not_suitable');
	private AICS_Content_Idea_Repository $ideas;private AICS_Article_Repository $articles;private AICS_Automation_Run_Repository $runs;private AICS_Automation_Profile_Repository $profiles;
	public function __construct(?AICS_Content_Idea_Repository $ideas=null,?AICS_Article_Repository $articles=null,?AICS_Automation_Run_Repository $runs=null,?AICS_Automation_Profile_Repository $profiles=null){$this->ideas=$ideas??new AICS_Content_Idea_Repository();$this->articles=$articles??new AICS_Article_Repository();$this->runs=$runs??new AICS_Automation_Run_Repository();$this->profiles=$profiles??new AICS_Automation_Profile_Repository();}
	public function approve_idea($idea_id,$user_id):array{$id=absint($idea_id);$user=absint($user_id);$idea=$this->ideas->get_by_id($id);if(!$idea||0===$user){return $this->result(false,'approval_item_missing','idea_id',$id,0);}if(!$this->valid_idea($idea)){return $this->result(false,'idea_decision_conflict','idea_id',$id,$idea['run_id']);}if(in_array($idea['status'],array('queued','article_generating','article_generated','completed'),true)){$resume=$this->resume_idea_run_if_ready($idea['run_id']);return $this->result(true,'idea_already_approved','idea_id',$id,$idea['run_id'],$resume['code']);}if('approved'===$idea['status']){$queued=$this->ideas->transition_status($id,array('approved'),'queued',array('updated_by'=>$user));if(!$queued['success']){return $this->result(false,'idea_decision_conflict','idea_id',$id,$idea['run_id']);}$resume=$this->resume_idea_run_if_ready($idea['run_id']);return $this->result(true,'idea_already_approved','idea_id',$id,$idea['run_id'],$resume['code']);}if('pending_approval'!==$idea['status']){return $this->result(false,'idea_decision_conflict','idea_id',$id,$idea['run_id']);}$profile=$this->profiles->get_by_id($idea['profile_id']);if(!$profile){return $this->result(false,'approval_item_missing','idea_id',$id,$idea['run_id']);}$limit=max(1,min(absint($profile['content_settings']['ideas_per_cycle']??1),absint($profile['content_settings']['selected_ideas_per_cycle']??1)));$selected=$this->ideas->count_ideas(array('run_id'=>$idea['run_id'],'statuses'=>array('approved','queued','article_generating','article_generated','completed')));if($selected>=$limit){return $this->result(false,'idea_approval_limit_reached','idea_id',$id,$idea['run_id']);}$approved=$this->ideas->transition_status($id,array('pending_approval'),'approved',array('updated_by'=>$user,'approved_by'=>$user));if(!$approved['success']){return $this->result(false,'idea_decision_conflict','idea_id',$id,$idea['run_id']);}$queued=$this->ideas->transition_status($id,array('approved'),'queued',array('updated_by'=>$user));if(!$queued['success']){return $this->result(false,'idea_decision_conflict','idea_id',$id,$idea['run_id']);}$resume=$this->resume_idea_run_if_ready($idea['run_id']);return $this->result(true,'idea_approved','idea_id',$id,$idea['run_id'],$resume['code']);}
	public function reject_idea($idea_id,$user_id,$code):array{$id=absint($idea_id);$user=absint($user_id);$code=sanitize_key(is_scalar($code)?(string)$code:'');$idea=$this->ideas->get_by_id($id);if(!$idea||0===$user){return $this->result(false,'approval_item_missing','idea_id',$id,0);}if(!in_array($code,self::IDEA_REJECTIONS,true)){return $this->result(false,'invalid_rejection_reason','idea_id',$id,$idea['run_id']);}if('pending_approval'!==$idea['status']||!$this->valid_idea($idea)){return $this->result(false,'idea_decision_conflict','idea_id',$id,$idea['run_id']);}$changed=$this->ideas->transition_status($id,array('pending_approval'),'rejected',array('updated_by'=>$user,'rejected_by'=>$user,'rejection_code'=>$code));if(!$changed['success']){return $this->result(false,'idea_decision_conflict','idea_id',$id,$idea['run_id']);}$resume=$this->resume_idea_run_if_ready($idea['run_id']);return $this->result(true,'idea_rejected','idea_id',$id,$idea['run_id'],$resume['code']);}
	public function approve_article($article_id,$user_id):array{$id=absint($article_id);$user=absint($user_id);$a=$this->articles->get_by_id($id);if(!$a||0===$user){return $this->result(false,'approval_item_missing','article_id',$id,0);}if(in_array($a['status'],array('approved','draft_created','scheduled','published'),true)){$resume=$this->resume_article_run_if_ready($a['run_id']);return $this->result(true,'article_already_approved','article_id',$id,$a['run_id'],$resume['code']);}if('pending_approval'!==$a['status']||!$this->valid_article($a)){return $this->result(false,'article_decision_conflict','article_id',$id,$a['run_id']);}$changed=$this->articles->transition_status($id,array('pending_approval'),'approved',array('updated_by'=>$user,'approved_by'=>$user));if(!$changed['success']){return $this->result(false,'article_decision_conflict','article_id',$id,$a['run_id']);}$resume=$this->resume_article_run_if_ready($a['run_id']);return $this->result(true,'article_approved','article_id',$id,$a['run_id'],$resume['code']);}
	public function reject_article($article_id,$user_id,$code):array{$id=absint($article_id);$user=absint($user_id);$code=sanitize_key(is_scalar($code)?(string)$code:'');$a=$this->articles->get_by_id($id);if(!$a||0===$user){return $this->result(false,'approval_item_missing','article_id',$id,0);}if(!in_array($code,self::ARTICLE_REJECTIONS,true)){return $this->result(false,'invalid_rejection_reason','article_id',$id,$a['run_id']);}if('pending_approval'!==$a['status']||!$this->valid_article($a)){return $this->result(false,'article_decision_conflict','article_id',$id,$a['run_id']);}$changed=$this->articles->transition_status($id,array('pending_approval'),'rejected',array('updated_by'=>$user,'rejected_by'=>$user,'rejection_code'=>$code));if(!$changed['success']){return $this->result(false,'article_decision_conflict','article_id',$id,$a['run_id']);}$resume=$this->resume_article_run_if_ready($a['run_id']);return $this->result(true,'article_rejected','article_id',$id,$a['run_id'],$resume['code']);}
	public function resume_idea_run_if_ready($run_id):array{$id=absint($run_id);$pending=$this->ideas->count_ideas(array('run_id'=>$id,'status'=>'pending_approval'));if($pending>0){return array('success'=>true,'code'=>'run_waiting_for_more_decisions','run_id'=>$id);}$selected=$this->ideas->count_ideas(array('run_id'=>$id,'statuses'=>array('approved','queued','article_generating','article_generated','completed')));return $selected>0?$this->runs->transition_waiting_step($id,'waiting_idea_approval','queue_idea'):$this->runs->fail_waiting_run($id,'waiting_idea_approval','all_ideas_rejected');}
	public function resume_article_run_if_ready($run_id):array{$id=absint($run_id);$pending=$this->articles->count_articles(array('run_id'=>$id,'status'=>'pending_approval'));if($pending>0){return array('success'=>true,'code'=>'run_waiting_for_more_decisions','run_id'=>$id);}$approved=$this->articles->count_articles(array('run_id'=>$id,'statuses'=>array('approved','draft_created','scheduled','published')));return $approved>0?$this->runs->transition_waiting_step($id,'waiting_article_approval','create_post'):$this->runs->fail_waiting_run($id,'waiting_article_approval','all_articles_rejected');}
	private function valid_idea(array $i):bool{return 'automation'===$i['source_type']&&$i['profile_id']>0&&$i['run_id']>0&&null!==$this->runs->get_by_id($i['run_id'])&&null!==$this->profiles->get_by_id($i['profile_id']);}
	private function valid_article(array $a):bool{return $a['profile_id']>0&&$a['run_id']>0&&$a['idea_id']>0&&''!==trim($a['title'])&&''!==trim($a['excerpt'])&&''!==trim($a['content'])&&64===strlen($a['content_hash'])&&null!==$a['generated_at']&&null!==$this->ideas->get_by_id($a['idea_id'])&&null!==$this->runs->get_by_id($a['run_id']);}
	private function result(bool $success,string $code,string $key,int $id,int $run,string $run_code=''):array{return array('success'=>$success,'code'=>$code,$key=>$id,'run_id'=>$run,'run_code'=>$run_code);}
}
