<?php
/** Processes one supported automation workflow step per cron invocation. @package AIContentStudio */
if ( ! defined( 'ABSPATH' ) ) { exit; }

final class AICS_Automation_Worker {
	private AICS_Automation_Run_Repository $runs;private AICS_Automation_Profile_Repository $profiles;private AICS_Content_Idea_Repository $ideas;private AICS_Automation_Idea_Generator $generator;
	public function __construct(?AICS_Automation_Run_Repository $runs=null,?AICS_Automation_Profile_Repository $profiles=null,?AICS_Content_Idea_Repository $ideas=null,?AICS_Automation_Idea_Generator $generator=null){$this->runs=$runs??new AICS_Automation_Run_Repository();$this->profiles=$profiles??new AICS_Automation_Profile_Repository();$this->ideas=$ideas??new AICS_Content_Idea_Repository();$this->generator=$generator??new AICS_Automation_Idea_Generator(null,$this->ideas);}

	public function process():array{$result=array('success'=>true,'code'=>'no_claimable_runs','runs_checked'=>0,'runs_claimed'=>0,'ideas_created'=>0,'duplicates'=>0);try{$now=current_time('mysql',true);$candidates=$this->runs->get_claimable_runs($now,array('pending','generate_ideas'),1);if(empty($candidates)){return $result;}$result['runs_checked']=1;$candidate=$candidates[0];$claim=$this->runs->claim_run($candidate['id'],900);if(!($claim['success']??false)){$result['success']=false;$result['code']='run_claim_failed';return $result;}$result['runs_claimed']=1;$token=$claim['lock_token'];$run=$this->runs->get_by_id($candidate['id']);if(!$run){$result['success']=false;$result['code']='run_missing_after_claim';return $result;}$profile=$this->profiles->get_by_id($run['profile_id']);if(!$profile){$this->runs->mark_failed($run['id'],$token,'automation_profile_missing');$result['success']=false;$result['code']='automation_profile_missing';return $result;}if('active'!==$profile['status']){$this->runs->cancel_claimed_run($run['id'],$token,'profile_not_active');$result['code']='profile_not_active';return $result;}if(!in_array($run['current_step'],array('pending','generate_ideas'),true)){$this->runs->release_lock($run['id'],$token);$result['code']='unsupported_run_step';return $result;}
		if($this->ideas->count_ideas(array('run_id'=>$run['id']))>0){if(!($this->runs->update_step($run['id'],$token,'evaluate_ideas')['success']??false)){$result['success']=false;$result['code']='run_step_update_failed';return $result;}$this->runs->release_lock($run['id'],$token);$result['code']='ideas_already_generated';return $result;}
		if('pending'===$run['current_step']&&!($this->runs->update_step($run['id'],$token,'generate_ideas')['success']??false)){$result['success']=false;$result['code']='run_step_update_failed';return $result;}
		$generated=$this->generator->generate($profile,$run['id']);if(!($this->runs->refresh_lock($run['id'],$token,900)['success']??false)){$result['success']=false;$result['code']='run_lock_lost';return $result;}if($generated['success']){$result['ideas_created']=absint($generated['created']);$result['duplicates']=absint($generated['batch_duplicates'])+absint($generated['historical_duplicates']);if(!($this->runs->update_step($run['id'],$token,'evaluate_ideas')['success']??false)){$result['success']=false;$result['code']='run_step_update_failed';return $result;}if(!($this->runs->release_lock($run['id'],$token)['success']??false)){$result['success']=false;$result['code']='run_lock_release_failed';return $result;}$result['code']='worker_completed';return $result;}
		$result['success']=false;$result['code']=$generated['code'];$fresh=$this->runs->get_by_id($run['id']);$attempt=absint($fresh['attempt_count']??1);$max=absint($fresh['max_attempts']??3);if($generated['retryable']&&$attempt<$max){$delays=array(1=>15,2=>60);$minutes=$delays[$attempt]??240;$retry=(new DateTimeImmutable('now',new DateTimeZone('UTC')))->modify('+'.$minutes.' minutes')->format('Y-m-d H:i:s');$scheduled=$this->runs->schedule_retry($run['id'],$token,$generated['code'],$retry);if(!($scheduled['success']??false)){$this->runs->mark_failed($run['id'],$token,'retry_scheduling_failed');$result['code']='retry_scheduling_failed';}return $result;}$this->runs->mark_failed($run['id'],$token,$generated['code']);return $result;
	}catch(Throwable $exception){$result['success']=false;$result['code']='unexpected_worker_error';if(defined('WP_DEBUG')&&WP_DEBUG){error_log('AI Content Studio worker stopped with controlled code: unexpected_worker_error');}return $result;}}
}
