<?php
/** AI-assisted scoring and deterministic idea routing. @package AIContentStudio */
if(!defined('ABSPATH')){exit;}
final class AICS_Automation_Idea_Evaluator{
	public const MINIMUM_ELIGIBLE_SCORE=60.00;private AICS_AI_Engine $engine;private AICS_Content_Idea_Repository $ideas;
	public function __construct(?AICS_AI_Engine $engine=null,?AICS_Content_Idea_Repository $ideas=null){$this->engine=$engine??new AICS_AI_Engine();$this->ideas=$ideas??new AICS_Content_Idea_Repository();}
	public function evaluate(array $profile,$run_id):array{$r=$this->base();$run_id=absint($run_id);$profile_id=absint($profile['id']??0);$all=$this->ideas->get_ideas_for_run($run_id,array('limit'=>20,'orderby'=>'created_at','order'=>'ASC'));$all=array_values(array_filter($all,static fn($i)=>$i['profile_id']===$profile_id&&'automation'===$i['source_type']));if(0===$run_id||0===$profile_id||empty($all)){$r['code']='missing_generated_ideas';return $r;}$unevaluated=array_values(array_filter($all,static fn($i)=>'generated'===$i['status']&&null===$i['evaluated_at']));
		if($unevaluated){if(!AICS_Settings::has_openai_api_key()){$r['code']='missing_api_configuration';return $r;}$map=array();$candidates=array();foreach(array_slice($unevaluated,0,20) as $index=>$idea){$key='candidate_'.($index+1);$map[$key]=$idea['id'];$candidates[]=array('candidate_id'=>$key,'title'=>$idea['title'],'summary'=>$idea['summary'],'primary_keyword'=>$idea['primary_keyword'],'search_intent'=>$idea['search_intent']);}$started=microtime(true);$response=$this->engine->evaluate_automation_ideas(is_array($profile['business_context']??null)?$profile['business_context']:array(),is_array($profile['content_settings']??null)?$profile['content_settings']:array(),$candidates);$duration=AICS_Usage_Logger::duration_ms($started);if(!$response->is_success()){$code=$this->provider_code($response->get_error_code());$this->log($run_id,false,$code,$duration,0,0);$r['code']=$code;$r['retryable']=$this->retryable($response->get_error_code());return $r;}$data=$response->get_data();if(!is_array($data)||!isset($data['evaluations'])||!is_array($data['evaluations'])){$this->log($run_id,false,'missing_evaluations_array',$duration,0,0);$r['code']='missing_evaluations_array';$r['retryable']=true;return $r;}$seen=array();foreach(array_slice($data['evaluations'],0,20) as $item){$score=$this->score_item($item,$map,$seen);if(null===$score){++$r['invalid_items'];continue;}$id=$map[$item['candidate_id']];$stored=$this->ideas->store_evaluation($id,$score,0);if($stored['success']){++$r['evaluated'];if($score>=self::MINIMUM_ELIGIBLE_SCORE){++$r['eligible'];}}else{++$r['invalid_items'];}}$remaining=$this->ideas->get_unevaluated_ideas_for_run($run_id,20);$success=empty($remaining);$this->log($run_id,$success,$success?'':'idea_evaluation_partial',$duration,$r['evaluated'],$r['eligible']);if(!$success){$r['code']='idea_evaluation_partial';$r['retryable']=true;return $r;}}
		return $this->route($profile,$run_id,$r);
	}
	private function route(array $profile,int $run_id,array $r):array{$all=$this->ideas->get_ideas_for_run($run_id,array('limit'=>20,'orderby'=>'created_at','order'=>'ASC'));$generated=array_values(array_filter($all,static fn($i)=>'generated'===$i['status']&&null!==$i['evaluated_at']));$approval='approval'===($profile['mode']??'')&&!empty($profile['workflow_rules']['require_idea_approval']);if($approval){foreach($generated as $idea){$this->ideas->transition_status($idea['id'],array('generated'),$idea['score']>=self::MINIMUM_ELIGIBLE_SCORE?'pending_approval':'rejected',$idea['score']>=self::MINIMUM_ELIGIBLE_SCORE?array('updated_by'=>0):array('updated_by'=>0,'rejection_code'=>'below_quality_threshold'));}$counts=$this->ideas->count_ideas_for_run_by_status($run_id);if(absint($counts['pending_approval']??0)>0){$r['success']=true;$r['code']='ideas_routed_for_approval';$r['next_step']='waiting_idea_approval';return $r;}$r['code']='no_eligible_ideas';return $r;}
		$selected=max(1,min(20,absint($profile['content_settings']['selected_ideas_per_cycle']??1)));$already=count(array_filter($all,static fn($i)=>in_array($i['status'],array('approved','queued'),true)));$eligible=array_values(array_filter($generated,static fn($i)=>$i['score']>=self::MINIMUM_ELIGIBLE_SCORE));usort($eligible,static function($a,$b){return ($b['score']<=>$a['score'])?:($b['priority']<=>$a['priority'])?:strcmp($a['created_at'],$b['created_at'])?:($a['id']<=>$b['id']);});$chosen=array_flip(array_map(static fn($i)=>$i['id'],array_slice($eligible,0,max(0,$selected-$already))));foreach($generated as $idea){if($idea['score']<self::MINIMUM_ELIGIBLE_SCORE){$this->ideas->transition_status($idea['id'],array('generated'),'rejected',array('updated_by'=>0,'rejection_code'=>'below_quality_threshold'));}elseif(isset($chosen[$idea['id']])){$approved=$this->ideas->transition_status($idea['id'],array('generated'),'approved',array('updated_by'=>0,'approved_by'=>0));if($approved['success']){$this->ideas->transition_status($idea['id'],array('approved'),'queued',array('updated_by'=>0));}}else{$this->ideas->transition_status($idea['id'],array('generated'),'rejected',array('updated_by'=>0,'rejection_code'=>'not_selected_for_cycle'));}}foreach($all as $idea){if('approved'===$idea['status']){$this->ideas->transition_status($idea['id'],array('approved'),'queued',array('updated_by'=>0));}}$counts=$this->ideas->count_ideas_for_run_by_status($run_id);if(absint($counts['queued']??0)>0){$r['success']=true;$r['code']='ideas_selected_and_queued';$r['next_step']='queue_idea';return $r;}$r['code']='no_eligible_ideas';return $r;}
	private function score_item($item,array $map,array &$seen):?float{if(!is_array($item)||!isset($item['candidate_id'])||!is_string($item['candidate_id'])||!isset($map[$item['candidate_id']])||isset($seen[$item['candidate_id']])){return null;}$seen[$item['candidate_id']]=true;$ranges=array('business_relevance'=>30,'audience_value'=>25,'content_depth'=>20,'originality'=>15,'search_intent_fit'=>10);$total=0.0;foreach($ranges as $key=>$max){if(!isset($item[$key])||!is_numeric($item[$key])||(float)$item[$key]<0||(float)$item[$key]>$max){return null;}$total+=(float)$item[$key];}return round($total,2);}
	private function provider_code(string $code):string{$map=array('missing-api-key'=>'missing_api_configuration','invalid-api-key'=>'invalid_api_configuration','rate-limit'=>'provider_rate_limit','network-error'=>'provider_network_error','invalid-response'=>'invalid_evaluation_json','invalid-idea-format'=>'invalid_evaluation_json','quota-error'=>'provider_quota_error','model-unavailable'=>'provider_model_unavailable');return $map[$code]??'provider_request_failed';}
	private function retryable(string $code):bool{return !in_array($code,array('missing-api-key','invalid-api-key','quota-error','model-unavailable','unsupported-task','invalid-evaluation-input'),true);}
	private function log(int $run,bool $success,string $code,int $duration,int $evaluated,int $eligible):void{AICS_Usage_Logger::log(array('user_id'=>0,'event_type'=>'ai_request','operation'=>'evaluate_content_ideas','status'=>$success?'success':'failed','provider'=>'openai','model'=>AICS_Settings::get_openai_model(),'error_code'=>$code,'object_id'=>$run,'duration_ms'=>$duration,'metadata'=>array('evaluated_count'=>$evaluated,'eligible_count'=>$eligible,'source'=>'automation')));}
	private function base():array{return array('success'=>false,'code'=>'evaluation_not_started','retryable'=>false,'evaluated'=>0,'eligible'=>0,'invalid_items'=>0,'next_step'=>'');}
}
