<?php
/** Shared featured-image prompt and provider generation coordinator. @package AIContentStudio */
if ( ! defined( 'ABSPATH' ) ) { exit; }

final class AICS_Featured_Image_Generation_Service {
	private AICS_Featured_Image_Prompt_Builder $prompt_builder;
	public function __construct(?AICS_Featured_Image_Prompt_Builder $prompt_builder=null){$this->prompt_builder=$prompt_builder??new AICS_Featured_Image_Prompt_Builder();}
	public function generate(array $context,bool $require_enabled=true):AICS_Image_Generation_Result{$settings=is_array($context['_immutable_settings']??null)?$context['_immutable_settings']:AICS_Featured_Image_Settings::get_effective();unset($context['_immutable_settings']);return $this->generate_with_settings($context,$settings,$require_enabled);}
	public function generate_with_settings(array $context,array $settings,bool $require_enabled=true):AICS_Image_Generation_Result{if($require_enabled&&empty($settings['enabled'])){return AICS_Image_Generation_Result::failure('image_generation_disabled',__('Featured-image generation is disabled.','ai-content-studio'),(string)($settings['provider']??''),false,0,(string)($settings['model']??''));}$validated=AICS_Featured_Image_Settings::validate($settings);if(is_wp_error($validated)){return AICS_Image_Generation_Result::failure('featured_image_configuration_invalid',__('The saved image configuration is invalid.','ai-content-studio'));}$settings=array_merge($validated,array('enabled'=>!empty($settings['enabled'])));$provider=AICS_Image_Provider_Factory::create($settings['provider']);if(is_wp_error($provider)){return AICS_Image_Generation_Result::failure('image_generation_not_supported',__('The configured image provider is not supported.','ai-content-studio'));}$configuration=$provider->validate_configuration();if(!$configuration['success']){return AICS_Image_Generation_Result::failure('image_provider_not_configured',$configuration['message'],$settings['provider'],false,0,$settings['model']);}$context['aspect_ratio']=$settings['aspect_ratio'];$context['visual_style']=$settings['visual_style'];$prompt=array_key_exists('final_prompt',$context)?AICS_Featured_Image_Prompt_Builder::sanitize_final_prompt($context['final_prompt']):$this->prompt_builder->build($context);if(is_wp_error($prompt)){return AICS_Image_Generation_Result::failure($prompt->get_error_code(),$prompt->get_error_message(),$settings['provider'],false,0,$settings['model']);}$request_data=array('prompt'=>$prompt,'aspect_ratio'=>$settings['aspect_ratio'],'quality'=>$settings['quality'],'output_format'=>$settings['output_format'],'provider'=>$settings['provider'],'model'=>$settings['model']);if(array_key_exists('article_id',$context)){$request_data['article_id']=$context['article_id'];}$request=AICS_Image_Generation_Request::from_array($request_data);if(is_wp_error($request)){return AICS_Image_Generation_Result::failure($request->get_error_code(),$request->get_error_message(),$settings['provider'],false,0,$settings['model']);}return $provider->generate($request);}
}
